name: sync-rule
version: 1.0.0
description: Sync rule
author: test
enabled: true
triggers:
  - type: commit
conditions: []
actions:
  - type: log
    message: Sync action
guards:
  max_retries: 3
  timeout: 300
  on_error: abort
