import { PricingData } from './types';

export const pricingData: PricingData = {
  offers: [
    {
      id: 'intensive-math-spring',
      type: 'intensive',
      eyebrow: 'Sessions Intensives',
      title: 'Mathématiques Intensif',
      description: 'Préparation intensive en mathématiques avec focus sur les sujets d\'examen. Groupes réduits de 6 personnes maximum.',
      price: 1890,
      originalPrice: 2490,
      discount: 24,
      groupSize: 6,
      duration: '6 semaines',
      intensity: '15h/semaine',
      startDate: 'Mars 2026',
      badge: 'NOUVEAU',
      badge_color: 'gold',
      placesAvailable: 3,
      placesLimit: 6,
      campaign: 'spring-2026',
      features: [
        '15 heures de cours par semaine',
        'Groupes de 6 élèves maximum',
        'Accès aux archives d\'examens',
        'Séances de débriefing hebdomadaires',
        'Support email illimité',
        'Accès à la plateforme Nexus',
      ],
      echeanciers: [
        { label: 'À l\'inscription', amount: 945, dueDate: '2026-01-15' },
        { label: 'Avant le démarrage', amount: 945, dueDate: '2026-02-15' },
      ],
      acompte: 945,
      acompteDeductible: true,
      cta: 'S\'inscrire maintenant',
      ctaAction: 'intensive-math',
    },
    {
      id: 'intensive-french-spring',
      type: 'intensive',
      eyebrow: 'Sessions Intensives',
      title: 'Français Intensif',
      description: 'Maîtrise de l\'écriture, de la lecture analytique et de l\'oral. Focus sur les techniques d\'examen.',
      price: 1890,
      originalPrice: 2490,
      discount: 24,
      groupSize: 6,
      duration: '6 semaines',
      intensity: '15h/semaine',
      startDate: 'Mars 2026',
      badge: 'POPULAIRE',
      badge_color: 'blue',
      placesAvailable: 2,
      placesLimit: 6,
      campaign: 'spring-2026',
      features: [
        '15 heures de cours par semaine',
        'Groupes de 6 élèves maximum',
        'Révision des œuvres au programme',
        'Préparation à l\'oral',
        'Analyse de dissertations corrigées',
        'Accès à la plateforme Nexus',
      ],
      echeanciers: [
        { label: 'À l\'inscription', amount: 945, dueDate: '2026-01-15' },
        { label: 'Avant le démarrage', amount: 945, dueDate: '2026-02-15' },
      ],
      acompte: 945,
      acompteDeductible: true,
      cta: 'S\'inscrire maintenant',
      ctaAction: 'intensive-french',
    },
    {
      id: 'annual-premium',
      type: 'annual',
      eyebrow: 'Offre Annuelle',
      title: 'Pass Premium Annuel',
      description: 'Accompagnement complet tout au long de l\'année avec cours, mentorat et suivi personnalisé.',
      price: 7490,
      originalPrice: 9990,
      discount: 25,
      groupSize: 8,
      duration: 'Septembre 2025 - Juin 2026',
      features: [
        'Cours en groupe (max 8 élèves)',
        'Mentorat personnel mensuel',
        'Accès complet à la plateforme',
        'Suivi des progrès avec dashboards',
        'Simulations d\'examens',
        'Support prioritaire',
        'Accès aux ressources premium',
        'Revue de copie illimitée',
      ],
      echeanciers: [
        { label: 'Acompte', amount: 2490, dueDate: '2025-06-15' },
        { label: '1er versement', amount: 2500, dueDate: '2025-09-15' },
        { label: '2e versement', amount: 2500, dueDate: '2026-01-15' },
      ],
      acompte: 2490,
      acompteDeductible: true,
      cta: 'Réserver ma place',
      ctaAction: 'annual-premium',
    },
    {
      id: 'annual-standard',
      type: 'annual',
      eyebrow: 'Offre Annuelle',
      title: 'Pass Standard Annuel',
      description: 'Accompagnement progressif avec cours collectifs et suivi régulier.',
      price: 4990,
      groupSize: 12,
      duration: 'Septembre 2025 - Juin 2026',
      features: [
        'Cours en groupe (max 12 élèves)',
        'Suivi mensuel',
        'Accès à la plateforme',
        'Ressources pédagogiques',
        'Forum de discussion',
        'Support par email',
        'Accès aux archives',
        'Révisions groupées',
      ],
      echeanciers: [
        { label: 'Acompte', amount: 1490, dueDate: '2025-06-15' },
        { label: '1er versement', amount: 1750, dueDate: '2025-09-15' },
        { label: '2e versement', amount: 1750, dueDate: '2026-01-15' },
      ],
      acompte: 1490,
      acompteDeductible: true,
      cta: 'Choisir ce pass',
      ctaAction: 'annual-standard',
    },
    {
      id: 'pass-flex-10',
      type: 'pass',
      eyebrow: 'Packs Flexibles',
      title: 'Pass Flexible 10 Sessions',
      description: 'Flexibilité maximum : 10 sessions utilisables sur 6 mois.',
      price: 1290,
      groupSize: 8,
      duration: 'Valable 6 mois',
      features: [
        '10 sessions de 2h avec des experts',
        'Flexibilité: réservez vos créneaux',
        'Accès à la plateforme',
        'Support par chat',
        'Ressources téléchargeables',
        'Sessions en groupes restreints',
      ],
      echeanciers: [
        { label: 'Paiement intégral', amount: 1290, dueDate: 'À l\'achat' },
      ],
      acompte: 1290,
      acompteDeductible: false,
      cta: 'Acheter le pass',
      ctaAction: 'pass-flex-10',
    },
    {
      id: 'pass-flex-5',
      type: 'pass',
      eyebrow: 'Packs Flexibles',
      title: 'Pass Flexible 5 Sessions',
      description: 'Idéal pour les candidats libres ou pour un complément ponctuel.',
      price: 690,
      groupSize: 8,
      duration: 'Valable 6 mois',
      features: [
        '5 sessions de 2h avec des experts',
        'Réservation flexible',
        'Accès à la plateforme',
        'Support par email',
        'Ressources de révision',
        'Sessions en petits groupes',
      ],
      echeanciers: [
        { label: 'Paiement intégral', amount: 690, dueDate: 'À l\'achat' },
      ],
      acompte: 690,
      acompteDeductible: false,
      cta: 'Acheter le pass',
      ctaAction: 'pass-flex-5',
    },
  ],

  passes: [
    {
      id: 'pass-10',
      title: 'Pass 10 Sessions',
      description: '10 sessions de 2h réparties sur 6 mois',
      value: 'Meilleure valeur',
      discount: 21,
      price: 1290,
      sessions: 10,
      validity: '6 mois',
    },
    {
      id: 'pass-5',
      title: 'Pass 5 Sessions',
      description: 'Parfait pour commencer',
      value: 'Flexibilité',
      discount: 15,
      price: 690,
      sessions: 5,
      validity: '6 mois',
    },
    {
      id: 'pass-20',
      title: 'Pass 20 Sessions',
      description: 'Accès complet sur un an',
      value: 'Maximum',
      discount: 30,
      price: 2190,
      sessions: 20,
      validity: '12 mois',
    },
  ],

  comparison: [
    {
      feature: 'Personnalisation du programme',
      nexus: 'Sur mesure pour chaque élève',
      traditional: 'Programme unique',
    },
    {
      feature: 'Taille des groupes',
      nexus: '6 à 8 élèves maximum',
      traditional: '20 à 30 élèves',
    },
    {
      feature: 'Suivi individualisé',
      nexus: 'Mentoring personnel inclus',
      traditional: 'Aucun',
    },
    {
      feature: 'Accès à la plateforme',
      nexus: '24h/24 avec ressources premium',
      traditional: 'Accès manuel ou très limité',
    },
    {
      feature: 'Revue de copie',
      nexus: 'Illimitée avec feedback détaillé',
      traditional: 'Paiement supplémentaire',
    },
    {
      feature: 'Flexibilité horaires',
      nexus: 'Options variées et flexibles',
      traditional: 'Horaires fixes',
    },
    {
      feature: 'Experts spécialisés',
      nexus: 'Professeurs certifiés & examinateurs',
      traditional: 'Professeurs généralistes',
    },
    {
      feature: 'Support entre les cours',
      nexus: 'Email, chat et forum',
      traditional: 'Aucun',
    },
  ],

  team: [
    {
      name: 'Dr. Marie Leclerc',
      role: 'Fondatrice & Directrice Pédagogique',
      bio: 'Docteur en Lettres modernes avec 15 ans d\'expérience. Examinatrice aux épreuves du bac.',
      image: '/team/marie.jpg',
      specialties: ['Français', 'Littérature', 'Épreuve orale'],
    },
    {
      name: 'Prof. Jean-Baptiste Moreau',
      role: 'Responsable Mathématiques',
      bio: 'Agrégé de mathématiques, 12 ans d\'enseignement. Corrige les copies du bac depuis 2014.',
      image: '/team/jb.jpg',
      specialties: ['Mathématiques', 'Spécialité Maths', 'Problème type'],
    },
    {
      name: 'Sophie Beaumont',
      role: 'Coach Méthodologie',
      bio: 'Spécialiste de la préparation aux examens. A aidé plus de 500 élèves à améliorer leurs notes.',
      image: '/team/sophie.jpg',
      specialties: ['Gestion du stress', 'Stratégie d\'examen', 'Motivation'],
    },
    {
      name: 'Prof. Antoine Rousseau',
      role: 'Spécialiste Histoire-Géo',
      bio: 'Expert en géopolitique et histoire contemporaine. 10 ans d\'expérience d\'enseignement.',
      image: '/team/antoine.jpg',
      specialties: ['Histoire-Géographie', 'Analyse de document', 'Croquis'],
    },
  ],

  faq: [
    {
      question: 'Comment fonctionne Académie Nexus ?',
      answer: 'Académie Nexus propose des cours en petits groupes (6-12 élèves) avec un accompagnement personnalisé. Vous choisissez entre des sessions intensives, un pass annuel, ou des packs flexibles selon vos besoins.',
      category: 'Généralités',
    },
    {
      question: 'Quels niveaux couvrez-vous ?',
      answer: 'Nous accompagnons tous les élèves de Première et Terminale, ainsi que les candidats libres, pour toutes les spécialités du baccalauréat général.',
      category: 'Généralités',
    },
    {
      question: 'Y a-t-il une garantie résultat ?',
      answer: 'Nous ne proposons pas de garantie « note », mais nos élèves améliorent leur moyenne de 2 à 4 points en moyenne. Nous sommes convaincus par nos méthodes et mettons l\'accent sur le suivi personnalisé.',
      category: 'Résultats',
    },
    {
      question: 'Puis-je annuler mon inscription ?',
      answer: 'Les annulations sont possibles jusqu\'à 2 semaines avant le début des sessions. L\'acompte versé ne sera pas remboursé en cas d\'annulation, mais peut être reporté.',
      category: 'Administratif',
    },
    {
      question: 'L\'acompte est-il déductible du prix total ?',
      answer: 'Oui, pour les passes annuels et intensifs, l\'acompte est entièrement déductible. Pour les packs flexibles, le prix affichés est le tarif final.',
      category: 'Tarification',
    },
    {
      question: 'Proposez-vous des cours en ligne ?',
      answer: 'Actuellement, nos cours sont en présentiel. Cependant, tous les élèves ont accès à une plateforme en ligne avec ressources, archives et forum de discussion.',
      category: 'Format',
    },
    {
      question: 'Comment puis-je m\'inscrire ?',
      answer: 'Vous pouvez vous inscrire directement via notre site. Un conseiller vous contactera pour valider votre inscription et répondre à vos questions.',
      category: 'Inscription',
    },
    {
      question: 'Avez-vous des réductions pour les familles ?',
      answer: 'Oui, à partir de 2 inscriptions dans la même famille, une réduction de 10 % est appliquée. Contactez-nous pour les modalités.',
      category: 'Tarification',
    },
  ],
};
