import type { EntryLevelCode } from './schema';

export const MAX_STUDENT_IDLE_MINUTES = 60;

/**
 * Richer replacement for the old binary "incompatible" flag (see
 * incompatibilities.ts, kept for its narrower simultaneity-only use). A real
 * student itinerary can be non-simultaneous yet still impose hours of dead
 * time — the UX rule (docs/campaigns/pre-rentree-2026/SCHEDULE-UX-AUDIT.md)
 * requires surfacing that, never collapsing it to a single boolean.
 *
 * - NO_SHARED_DAY: the selected subjects never fall on the same calendar date
 *   for this student — no idle time is generated by this pair/selection.
 * - COMPACT: every date where ≥2 selected subjects occur has a gap between
 *   consecutive sessions of at most MAX_STUDENT_IDLE_MINUTES.
 * - LONG_IDLE: at least one shared date has a gap exceeding
 *   MAX_STUDENT_IDLE_MINUTES between two sessions the student actually attends.
 * - SIMULTANEOUS: at least one shared date has two selected subjects in the
 *   same time block — physically impossible for one student.
 * - REQUIRES_ALTERNATIVE_COHORT: reserved for when alternative cohort data
 *   exists (see cohortId/alternativeGroupId in schema.ts) and picking a
 *   different cohort of one of the subjects would resolve a SIMULTANEOUS or
 *   LONG_IDLE conflict. Unreachable today: the canonical schedule has exactly
 *   one cohort per level/subject, so there is nothing to switch to yet.
 * - REQUIRES_MANUAL_REVIEW: the engine could not compute a confident status
 *   (e.g. malformed/inconsistent schedule data) — never silently reported as
 *   COMPACT.
 */
export type ItineraryStatus =
  | 'NO_SHARED_DAY'
  | 'COMPACT'
  | 'LONG_IDLE'
  | 'SIMULTANEOUS'
  | 'REQUIRES_ALTERNATIVE_COHORT'
  | 'REQUIRES_MANUAL_REVIEW';

export interface ItinerarySession {
  date: string;
  level: EntryLevelCode;
  subject: string;
  block: string;
  startTime: string;
  endTime: string;
  room?: string;
  windowId?: string;
  cohortId?: string;
  isPrimary?: boolean;
}

export interface DayItinerary {
  date: string;
  sessions: ItinerarySession[];
  idleGapsMinutes: number[];
  maxIdleMinutes: number;
  simultaneous: boolean;
}

export interface ItineraryReport {
  level: EntryLevelCode;
  subjects: readonly string[];
  status: ItineraryStatus;
  daysPresent: number;
  maxIdleMinutes: number;
  totalIdleMinutes: number;
  days: DayItinerary[];
  /** First blocking conflict found, if any — used for REQUIRES_MANUAL_REVIEW
   * and SIMULTANEOUS messaging without re-deriving it downstream. */
  firstConflict: { date: string; subjectA: string; subjectB: string; reason: 'SIMULTANEOUS' | 'LONG_IDLE'; idleMinutes?: number } | null;
}

function toMinutes(time: string): number {
  const [h, m] = time.split(':').map(Number);
  return h * 60 + m;
}

/**
 * Computes the real itinerary (day-by-day idle time) for one student following
 * exactly the given subjects at the given level, from the canonical dated
 * schedule. A subject NOT in `subjects` never counts as occupying idle time,
 * even if another cohort of that subject exists on the same date/block
 * (rule 4 of the UX audit): we only ever look at `sessions` already filtered
 * to `subjects`.
 */
export function computeItinerary(
  level: EntryLevelCode,
  subjects: readonly string[],
  allSessions: readonly ItinerarySession[],
): ItineraryReport {
  const relevant = allSessions.filter(
    (session) => session.level === level && subjects.includes(session.subject),
  );

  const byDate = new Map<string, ItinerarySession[]>();
  for (const session of relevant) {
    const list = byDate.get(session.date) ?? [];
    list.push(session);
    byDate.set(session.date, list);
  }

  const days: DayItinerary[] = [];
  let firstConflict: ItineraryReport['firstConflict'] = null;
  let overallMaxIdle = 0;
  let totalIdle = 0;
  let anySimultaneous = false;
  let anyLongIdle = false;
  let anySharedDay = false;

  for (const [date, daySessions] of [...byDate.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const sorted = [...daySessions].sort((a, b) => toMinutes(a.startTime) - toMinutes(b.startTime));
    const gaps: number[] = [];
    let daySimultaneous = false;
    let dayMaxIdle = 0;

    if (sorted.length >= 2) {
      anySharedDay = true;
    }

    for (let i = 0; i < sorted.length - 1; i += 1) {
      const current = sorted[i]!;
      const next = sorted[i + 1]!;
      const gap = toMinutes(next.startTime) - toMinutes(current.endTime);
      if (gap < 0 && toMinutes(current.startTime) === toMinutes(next.startTime)) {
        daySimultaneous = true;
        anySimultaneous = true;
        if (!firstConflict) {
          firstConflict = { date, subjectA: current.subject, subjectB: next.subject, reason: 'SIMULTANEOUS' };
        }
        continue;
      }
      if (gap < 0) {
        // Overlapping but not identical start (should not occur with the current
        // fixed 2h blocks) — treat conservatively as a review case, not a silent pass.
        if (!firstConflict) {
          firstConflict = { date, subjectA: current.subject, subjectB: next.subject, reason: 'SIMULTANEOUS' };
        }
        daySimultaneous = true;
        anySimultaneous = true;
        continue;
      }
      gaps.push(gap);
      totalIdle += gap;
      dayMaxIdle = Math.max(dayMaxIdle, gap);
      if (gap > MAX_STUDENT_IDLE_MINUTES) {
        anyLongIdle = true;
        if (!firstConflict) {
          firstConflict = { date, subjectA: current.subject, subjectB: next.subject, reason: 'LONG_IDLE', idleMinutes: gap };
        }
      }
    }

    overallMaxIdle = Math.max(overallMaxIdle, dayMaxIdle);
    days.push({ date, sessions: sorted, idleGapsMinutes: gaps, maxIdleMinutes: dayMaxIdle, simultaneous: daySimultaneous });
  }

  let status: ItineraryStatus;
  if (anySimultaneous) {
    status = 'SIMULTANEOUS';
  } else if (anyLongIdle) {
    status = 'LONG_IDLE';
  } else if (anySharedDay) {
    status = 'COMPACT';
  } else {
    status = 'NO_SHARED_DAY';
  }

  return {
    level,
    subjects,
    status,
    daysPresent: byDate.size,
    maxIdleMinutes: overallMaxIdle,
    totalIdleMinutes: totalIdle,
    days,
    firstConflict,
  };
}

/** All non-empty subsets of `subjects` up to `maxSize`, smallest first. */
export function enumerateSelections(subjects: readonly string[], maxSize: number): string[][] {
  const results: string[][] = [];
  const n = subjects.length;
  for (let mask = 1; mask < 1 << n; mask += 1) {
    const selection: string[] = [];
    for (let bit = 0; bit < n; bit += 1) {
      if (mask & (1 << bit)) selection.push(subjects[bit]!);
    }
    if (selection.length <= maxSize) results.push(selection);
  }
  return results.sort((a, b) => a.length - b.length || a.join(',').localeCompare(b.join(',')));
}

export interface AssignmentResult {
  level: EntryLevelCode;
  subjects: readonly string[];
  /** subject -> chosen cohortId (undefined when the subject has a single/primary cohort) */
  cohortBySubject: Record<string, string | undefined>;
  /** subject -> that cohort's 5 sessions */
  sessionsBySubject: Record<string, ItinerarySession[]>;
  itinerary: ItineraryReport;
}

function cohortGroups(subject: string, sessions: readonly ItinerarySession[]): Array<{ cohortId: string | undefined; isPrimary: boolean; sessions: ItinerarySession[] }> {
  const bySubject = sessions.filter((s) => s.subject === subject);
  const groups = new Map<string | undefined, ItinerarySession[]>();
  for (const session of bySubject) {
    const list = groups.get(session.cohortId) ?? [];
    list.push(session);
    groups.set(session.cohortId, list);
  }
  return [...groups.entries()].map(([cohortId, sess]) => ({
    cohortId,
    isPrimary: sess[0]?.isPrimary ?? true,
    sessions: sess,
  }));
}

/**
 * The itinerary ASSIGNMENT engine (as opposed to computeItinerary, which
 * scores one already-fixed set of sessions): given a level and the subjects a
 * family actually selected, and every session available for this level
 * (including every alternative cohort), tries every combination of cohort
 * choices and returns the one minimizing, in order: simultaneity, long idle
 * time, total idle time, then a determinstic preference for primary cohorts
 * and cohort id order (never a random/unstable pick).
 *
 * A subject with only one cohort (no cohortId, or a single cohortId group)
 * has nothing to choose — this degrades to exactly the old single-cohort
 * behaviour. Never selects more than one cohort per subject: the caller
 * always gets exactly 5 sessions per selected subject, never 10.
 */
export function assignItinerary(
  level: EntryLevelCode,
  subjects: readonly string[],
  allSessions: readonly ItinerarySession[],
): AssignmentResult {
  const levelSessions = allSessions.filter((s) => s.level === level);
  const optionsPerSubject = subjects.map((subject) => cohortGroups(subject, levelSessions));

  optionsPerSubject.forEach((options, i) => {
    if (options.length === 0) {
      throw new Error(`Missing campaign schedule for ${level}/${subjects[i]}`);
    }
  });

  const rank = (r: ItineraryReport, penalty: number): [number, number, number, number] => [
    r.status === 'SIMULTANEOUS' ? 1 : 0,
    r.status === 'LONG_IDLE' ? 1 : 0,
    r.maxIdleMinutes,
    penalty,
  ];
  const lexLess = (a: readonly number[], b: readonly number[]): boolean => {
    for (let i = 0; i < a.length; i += 1) {
      if (a[i]! !== b[i]!) return a[i]! < b[i]!;
    }
    return false;
  };

  let best: { report: ItineraryReport; choice: typeof optionsPerSubject[number][number][]; rank: [number, number, number, number] } | null = null;

  const totalCombinations = optionsPerSubject.reduce((acc, opts) => acc * opts.length, 1);
  for (let combo = 0; combo < totalCombinations; combo += 1) {
    let remainder = combo;
    const choice: typeof optionsPerSubject[number][number][] = [];
    for (let i = 0; i < optionsPerSubject.length; i += 1) {
      const options = optionsPerSubject[i]!;
      const idx = remainder % options.length;
      remainder = Math.floor(remainder / options.length);
      choice.push(options[idx]!);
    }
    const chosenSessions = choice.flatMap((c) => c.sessions);
    const report = computeItinerary(level, subjects, chosenSessions);
    const penalty = choice.filter((c) => !c.isPrimary).length;
    const candidateRank = rank(report, penalty);
    if (!best || lexLess(candidateRank, best.rank)) {
      best = { report, choice, rank: candidateRank };
    }
  }

  const cohortBySubject: Record<string, string | undefined> = {};
  const sessionsBySubject: Record<string, ItinerarySession[]> = {};
  subjects.forEach((subject, i) => {
    cohortBySubject[subject] = best!.choice[i]!.cohortId;
    sessionsBySubject[subject] = best!.choice[i]!.sessions;
  });

  return {
    level,
    subjects,
    cohortBySubject,
    sessionsBySubject,
    itinerary: best!.report,
  };
}

export function itineraryStatusLabel(status: ItineraryStatus): string {
  switch (status) {
    case 'NO_SHARED_DAY':
      return 'Aucune journée commune : ces matières ne se croisent jamais le même jour.';
    case 'COMPACT':
      return 'Parcours compact : aucune attente supérieure à 60 minutes.';
    case 'LONG_IDLE':
      return 'Cette combinaison impose une attente supérieure à 60 minutes le même jour.';
    case 'SIMULTANEOUS':
      return 'Ces matières ont un créneau simultané : elles ne peuvent pas être suivies ensemble.';
    case 'REQUIRES_ALTERNATIVE_COHORT':
      return 'Une autre cohorte permettrait de rendre ce parcours compact — à confirmer.';
    case 'REQUIRES_MANUAL_REVIEW':
      return 'Cette combinaison nécessite une revue manuelle du planning.';
    default:
      return status satisfies never;
  }
}
