version: '3.9'

services:
  postgres-test:
    image: pgvector/pgvector@sha256:a947c45cdc5906a1bc951f20a8709e321256343ee0f251e4ae00b5e7def4e6da # pg15
    container_name: nexus-postgres-test
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: nexus_user
      POSTGRES_PASSWORD: test_password_change_in_real_prod
      POSTGRES_DB: nexus_disposable_test
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=512m
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nexus_user -d nexus_disposable_test" ]
      interval: 5s
      timeout: 5s
      retries: 5
