import type { QcmQuestion } from './types';

export const QCM_BANK: QcmQuestion[] = [
  {
    id: 'sujet0_v1_q1',
    number: 1,
    source: 'sujet_0_v1',
    category: 'ROUGE',
    enonce: 'Dans une réserve, 25 % des singes sont des mâles. Parmi ces mâles, 80 % sont adultes. Quelle proportion des singes représente les mâles adultes ?',
    graphicAsset: 'survival/qcm/q1v1-courbe-2-solutions.svg',
    choices: [
      { letter: 'A', text: '20 %' },
      { letter: 'B', text: '25 %' },
      { letter: 'C', text: '80 %' },
      { letter: 'D', text: '105 %' },
    ],
    correctAnswer: 'A',
    pedagogicalHint: 'On calcule 25 % de 80 %, donc 0,25 × 0,80 = 0,20.',
  },
  {
    id: 'sujet0_v1_q2',
    number: 2,
    source: 'sujet_0_v1',
    category: 'ORANGE',
    reflexId: 'reflex_1',
    enonce: 'Un prix baisse de 50 %. De quel pourcentage faut-il l’augmenter pour retrouver le prix initial ?',
    choices: [
      { letter: 'A', text: '50 %' },
      { letter: 'B', text: '100 %' },
      { letter: 'C', text: '25 %' },
      { letter: 'D', text: '150 %' },
    ],
    correctAnswer: 'B',
    exclusionTip: 'Une baisse de 50 % divise par 2 : pour revenir, il faut doubler.',
  },
  {
    id: 'sujet0_v1_q3',
    number: 3,
    source: 'sujet_0_v1',
    category: 'VERT',
    reflexId: 'reflex_1',
    enonce: 'Une valeur passe de 250 à 200. Quel est le coefficient multiplicateur ?',
    choices: [
      { letter: 'A', text: '1,25' },
      { letter: 'B', text: '0,2' },
      { letter: 'C', text: '0,8' },
      { letter: 'D', text: '1,8' },
    ],
    correctAnswer: 'C',
    pedagogicalHint: 'Nouveau ÷ ancien : 200 ÷ 250 = 0,8.',
  },
  {
    id: 'sujet0_v1_q4',
    number: 4,
    source: 'sujet_0_v1',
    category: 'ROUGE',
    enonce: 'Quelle écriture est égale à (2⁻⁴)³ ?',
    choices: [
      { letter: 'A', text: '2⁻¹' },
      { letter: 'B', text: '2¹²' },
      { letter: 'C', text: '6⁻¹²' },
      { letter: 'D', text: '2⁻¹²' },
    ],
    correctAnswer: 'D',
    pedagogicalHint: 'Une puissance d’une puissance multiplie les exposants : -4 × 3 = -12.',
  },
  {
    id: 'sujet0_v1_q5',
    number: 5,
    source: 'sujet_0_v1',
    category: 'ROUGE',
    enonce: 'L’écriture scientifique de 3,2 × 10⁵ × 2000 est :',
    choices: [
      { letter: 'A', text: '6,4 × 10⁸' },
      { letter: 'B', text: '6,4 × 10⁷' },
      { letter: 'C', text: '3,2 × 10⁸' },
      { letter: 'D', text: '64 × 10⁷' },
    ],
    correctAnswer: 'A',
    pedagogicalHint: '2000 = 2 × 10³, donc 3,2 × 2 × 10⁸ = 6,4 × 10⁸.',
  },
  {
    id: 'sujet0_v1_q6',
    number: 6,
    source: 'sujet_0_v1',
    category: 'ROUGE',
    enonce: 'Parmi ces nombres, lequel est le plus grand ?',
    choices: [
      { letter: 'A', text: '4,2 × 10⁻³' },
      { letter: 'B', text: '7,1 × 10⁴' },
      { letter: 'C', text: '9,8 × 10²' },
      { letter: 'D', text: '1,2 × 10³' },
    ],
    correctAnswer: 'B',
    pedagogicalHint: 'Le plus grand exposant positif domine ici.',
  },
  {
    id: 'sujet0_v1_q7',
    number: 7,
    source: 'sujet_0_v1',
    category: 'VERT',
    reflexId: 'reflex_6',
    enonce: 'Quelle expression est égale à x + 3x + x² ?',
    choices: [
      { letter: 'A', text: '4x²' },
      { letter: 'B', text: '5x' },
      { letter: 'C', text: 'x² + 4x' },
      { letter: 'D', text: '3x²' },
    ],
    correctAnswer: 'C',
    pedagogicalHint: 'x + 3x = 4x, et x² reste séparé.',
  },
  {
    id: 'sujet0_v1_q8',
    number: 8,
    source: 'sujet_0_v1',
    category: 'ORANGE',
    reflexId: 'reflex_5',
    enonce: 'Sur le graphique, pour quelles valeurs de x a-t-on f(x) ≤ g(x) ?',
    graphicAsset: 'survival/qcm/q8v1-deux-courbes.svg',
    choices: [
      { letter: 'A', text: '[-4 ; -2] ∪ [2 ; 4]' },
      { letter: 'B', text: '[-2 ; 1]' },
      { letter: 'C', text: 'Aucune valeur' },
      { letter: 'D', text: '[-2 ; -1] ∪ [1 ; 2]' },
    ],
    correctAnswer: 'D',
    exclusionTip: 'On garde les zones où la courbe de f est sous celle de g.',
  },
  {
    id: 'sujet0_v1_q9',
    number: 9,
    source: 'sujet_0_v1',
    category: 'VERT',
    reflexId: 'reflex_5',
    enonce: 'Combien l’équation f(x)=0 admet-elle de solutions sur le graphique ?',
    graphicAsset: 'survival/qcm/q9v1-courbe-cubique.svg',
    choices: [
      { letter: 'A', text: '2' },
      { letter: 'B', text: '0' },
      { letter: 'C', text: '1' },
      { letter: 'D', text: '3' },
    ],
    correctAnswer: 'A',
    pedagogicalHint: 'On compte les points où la courbe coupe l’axe horizontal.',
  },
  {
    id: 'sujet0_v1_q10',
    number: 10,
    source: 'sujet_0_v1',
    category: 'ROUGE',
    enonce: 'Un tableau de valeurs correspond à une fonction affine si :',
    choices: [
      { letter: 'A', text: 'les images sont toutes positives' },
      { letter: 'B', text: 'les accroissements sont réguliers' },
      { letter: 'C', text: 'la première image vaut 0' },
      { letter: 'D', text: 'les valeurs de x sont négatives' },
    ],
    correctAnswer: 'B',
    pedagogicalHint: 'Pour une fonction affine, les écarts d’images sont réguliers quand les x avancent régulièrement.',
  },
  {
    id: 'sujet0_v1_q11',
    number: 11,
    source: 'sujet_0_v1',
    category: 'ROUGE',
    enonce: 'Si C = (1+t)² avec t > -1, alors t est égal à :',
    choices: [
      { letter: 'A', text: 'C - 1' },
      { letter: 'B', text: 'C² - 1' },
      { letter: 'C', text: '√C - 1' },
      { letter: 'D', text: '1 - √C' },
    ],
    correctAnswer: 'C',
    pedagogicalHint: 'On prend la racine : 1+t = √C, donc t = √C - 1.',
  },
  {
    id: 'sujet0_v1_q12',
    number: 12,
    source: 'sujet_0_v1',
    category: 'VERT',
    reflexId: 'reflex_5',
    enonce: 'D’après le diagramme en barres, quelle année a la production nucléaire la plus élevée ?',
    graphicAsset: 'survival/qcm/q12v1-diagramme-barres.svg',
    choices: [
      { letter: 'A', text: '1995' },
      { letter: 'B', text: '2001' },
      { letter: 'C', text: '2006' },
      { letter: 'D', text: '2016' },
    ],
    correctAnswer: 'D',
    pedagogicalHint: 'On lit la barre nucléaire la plus haute.',
  },
  {
    id: 'sujet0_v2_q1',
    number: 1,
    source: 'sujet_0_v2',
    category: 'VERT',
    reflexId: 'reflex_1',
    enonce: 'Un article coûte 400 euros. Son prix augmente de 20 %. Quel est le nouveau prix ?',
    choices: [
      { letter: 'A', text: '480 euros' },
      { letter: 'B', text: '420 euros' },
      { letter: 'C', text: '500 euros' },
      { letter: 'D', text: '320 euros' },
    ],
    correctAnswer: 'A',
    pedagogicalHint: '400 × 1,20 = 480.',
  },
  {
    id: 'sujet0_v2_q2',
    number: 2,
    source: 'sujet_0_v2',
    category: 'VERT',
    reflexId: 'reflex_1',
    enonce: 'Une baisse de 10 % correspond à un coefficient multiplicateur de :',
    choices: [
      { letter: 'A', text: '1,10' },
      { letter: 'B', text: '0,90' },
      { letter: 'C', text: '0,10' },
      { letter: 'D', text: '9' },
    ],
    correctAnswer: 'B',
    pedagogicalHint: 'Baisse de 10 %, donc on garde 90 %, soit 0,90.',
  },
  {
    id: 'sujet0_v2_q3',
    number: 3,
    source: 'sujet_0_v2',
    category: 'ORANGE',
    reflexId: 'reflex_1',
    enonce: 'Deux hausses successives de 20 % correspondent à quel coefficient multiplicateur ?',
    choices: [
      { letter: 'A', text: '1,40' },
      { letter: 'B', text: '0,64' },
      { letter: 'C', text: '1,44' },
      { letter: 'D', text: '2,40' },
    ],
    correctAnswer: 'C',
    exclusionTip: 'Deux hausses de 20 % ne font pas seulement +40 % : on multiplie 1,2 × 1,2.',
  },
  {
    id: 'sujet0_v2_q4',
    number: 4,
    source: 'sujet_0_v2',
    category: 'ROUGE',
    enonce: 'Dans une élection, un quart des voix va à A, 20 % à B, un tiers à C. Quelle part reste pour D ?',
    graphicAsset: 'survival/qcm/q12v2-diagramme-circulaire.svg',
    choices: [
      { letter: 'A', text: '1/4' },
      { letter: 'B', text: '1/3' },
      { letter: 'C', text: '1/5' },
      { letter: 'D', text: '13/60' },
    ],
    correctAnswer: 'D',
    pedagogicalHint: 'On met tout sur 60 : 15/60 + 12/60 + 20/60 = 47/60, il reste 13/60.',
  },
  {
    id: 'sujet0_v2_q5',
    number: 5,
    source: 'sujet_0_v2',
    category: 'ROUGE',
    enonce: 'Quel est le résultat de 1/2 - 1/3 + 1/6 ?',
    choices: [
      { letter: 'A', text: '1/3' },
      { letter: 'B', text: '0' },
      { letter: 'C', text: '1/6' },
      { letter: 'D', text: '2/3' },
    ],
    correctAnswer: 'A',
    pedagogicalHint: 'Sur 6 : 3/6 - 2/6 + 1/6 = 2/6 = 1/3.',
  },
  {
    id: 'sujet0_v2_q6',
    number: 6,
    source: 'sujet_0_v2',
    category: 'ORANGE',
    enonce: 'Calculer 1/100 + 1/1000.',
    choices: [
      { letter: 'A', text: '0,11' },
      { letter: 'B', text: '0,011' },
      { letter: 'C', text: '0,0011' },
      { letter: 'D', text: '0,101' },
    ],
    correctAnswer: 'B',
    pedagogicalHint: 'À mémoriser directement : 0,01 + 0,001 = 0,011.',
  },
  {
    id: 'sujet0_v2_q7',
    number: 7,
    source: 'sujet_0_v2',
    category: 'VERT',
    enonce: '75 minutes correspondent à :',
    choices: [
      { letter: 'A', text: '1,15 h' },
      { letter: 'B', text: '0,75 h' },
      { letter: 'C', text: '1,25 h' },
      { letter: 'D', text: '1,75 h' },
    ],
    correctAnswer: 'C',
    pedagogicalHint: '75 minutes = 60 minutes + 15 minutes = 1 h + 0,25 h.',
  },
  {
    id: 'sujet0_v2_q8',
    number: 8,
    source: 'sujet_0_v2',
    category: 'ROUGE',
    enonce: 'Le nombre 10³⁰ + 10⁻³⁰ est très proche de :',
    choices: [
      { letter: 'A', text: '0' },
      { letter: 'B', text: '10⁰' },
      { letter: 'C', text: '10⁻³⁰' },
      { letter: 'D', text: '10³⁰' },
    ],
    correctAnswer: 'D',
    pedagogicalHint: '10⁻³⁰ est minuscule devant 10³⁰.',
  },
  {
    id: 'sujet0_v2_q9',
    number: 9,
    source: 'sujet_0_v2',
    category: 'ORANGE',
    reflexId: 'reflex_5',
    enonce: 'Quelle droite représente la fonction y = -2x + 5 ?',
    graphicAsset: 'survival/qcm/q9v2-droite-y-equals-minus-2x-plus-5.svg',
    choices: [
      { letter: 'A', text: 'D3' },
      { letter: 'B', text: 'D1' },
      { letter: 'C', text: 'D4' },
      { letter: 'D', text: 'D2' },
    ],
    correctAnswer: 'A',
    exclusionTip: 'La droite cherchée est décroissante et coupe l’axe vertical en 5.',
  },
  {
    id: 'sujet0_v2_q10',
    number: 10,
    source: 'sujet_0_v2',
    category: 'VERT',
    reflexId: 'reflex_6',
    enonce: 'Résoudre l’équation 3x = 0.',
    choices: [
      { letter: 'A', text: 'x = 3' },
      { letter: 'B', text: 'x = 0' },
      { letter: 'C', text: 'x = 1/3' },
      { letter: 'D', text: 'Impossible' },
    ],
    correctAnswer: 'B',
    pedagogicalHint: 'Si ax = 0, alors x = 0.',
  },
  {
    id: 'sujet0_v2_q11',
    number: 11,
    source: 'sujet_0_v2',
    category: 'ORANGE',
    reflexId: 'reflex_6',
    enonce: 'Résoudre l’équation 144/x = 9.',
    choices: [
      { letter: 'A', text: 'x = 9' },
      { letter: 'B', text: 'x = 144' },
      { letter: 'C', text: 'x = 16' },
      { letter: 'D', text: 'x = 153' },
    ],
    correctAnswer: 'C',
    pedagogicalHint: '144 = 16 × 9, donc x = 16.',
  },
  {
    id: 'sujet0_v2_q12',
    number: 12,
    source: 'sujet_0_v2',
    category: 'ROUGE',
    enonce: 'La moyenne pondérée de trois notes est 12. Deux notes valent 10 et 14 avec le même coefficient. La troisième note, de coefficient 2, vaut :',
    graphicAsset: 'survival/qcm/q12v2-diagramme-circulaire.svg',
    choices: [
      { letter: 'A', text: '10' },
      { letter: 'B', text: '13' },
      { letter: 'C', text: '14' },
      { letter: 'D', text: '12' },
    ],
    correctAnswer: 'D',
    pedagogicalHint: 'Avec coefficients 1, 1, 2 : (10 + 14 + 2x) ÷ 4 = 12, donc x = 12.',
  },
];

// TODO: Shark fournira 30 questions simulées additionnelles dans une seconde itération.
