import type { SurvivalReflex } from './types';

export const REFLEXES: SurvivalReflex[] = [
  {
    id: 'reflex_1',
    order: 1,
    title: 'Hausse / baisse en pourcentage',
    hook: 'Hausse : on multiplie par 1 et quelque. Baisse : on multiplie par zero virgule quelque chose.',
    mentalImage: 'Un prix avec une etiquette + ou -.',
    whenToUse: ['augmente de', 'baisse de', 'remise de', 'indice base 100'],
    method: ['+10 % devient x 1,10', '-10 % devient x 0,90', 'nouveau / ancien donne le coefficient'],
    miniQuiz: [
      { id: 'reflex_1_q1', prompt: '200 euros augmente de 10 %. Nouveau prix ?', answer: '220 euros', explanation: '200 x 1,10 = 220.' },
      { id: 'reflex_1_q2', prompt: '80 euros avec remise de 25 %. Nouveau prix ?', answer: '60 euros', explanation: '80 x 0,75 = 60.' },
      { id: 'reflex_1_q3', prompt: 'Le prix passe de 50 a 60. Coefficient ?', answer: '1,2', explanation: '60 / 50 = 1,2.' },
    ],
    magicPhraseId: 'phrase_5',
    qcmPointsCovered: 0.5,
  },
  {
    id: 'reflex_2',
    order: 2,
    title: 'Suite arithmetique : on ajoute toujours',
    hook: '+50 par an : arithmetique, raison 50.',
    mentalImage: 'Un escalier a marches identiques.',
    whenToUse: ['ajoute', 'clients de plus', 'habitants supplementaires', 'chaque annee'],
    method: ['u(n+1) = u(n) + r', 'r est le nombre ajoute'],
    miniQuiz: [
      { id: 'reflex_2_q1', prompt: 'u0 = 100, on ajoute 5. u1 ?', answer: '105', explanation: '100 + 5 = 105.' },
      { id: 'reflex_2_q2', prompt: '5000 habitants, +100/an. Dans 10 ans ?', answer: '6000', explanation: '5000 + 10 x 100 = 6000.' },
      { id: 'reflex_2_q3', prompt: 'Raison 50, u0 = 1000. u1 ?', answer: '1050', explanation: '1000 + 50 = 1050.' },
    ],
    magicPhraseId: 'phrase_1',
    qcmPointsCovered: 0.35,
  },
  {
    id: 'reflex_3',
    order: 3,
    title: 'Suite geometrique : on multiplie toujours',
    hook: '+10 % par an : geometrique, raison 1,1.',
    mentalImage: 'Une boule de neige qui grossit.',
    whenToUse: ['augmente de t % chaque annee', 'baisse de t % par an'],
    method: ['u(n+1) = u(n) x q', 'q est le coefficient multiplicateur'],
    miniQuiz: [
      { id: 'reflex_3_q1', prompt: 'Population 1000, baisse 10 %. Au bout d un an ?', answer: '900', explanation: '1000 x 0,9 = 900.' },
      { id: 'reflex_3_q2', prompt: 'Capital 500, hausse 5 %. Au bout d un an ?', answer: '525', explanation: '500 x 1,05 = 525.' },
      { id: 'reflex_3_q3', prompt: 'Stock 1000, baisse 10 % deux fois ?', answer: '810', explanation: '1000 x 0,9 x 0,9 = 810.' },
    ],
    magicPhraseId: 'phrase_2',
    qcmPointsCovered: 0.35,
  },
  {
    id: 'reflex_4',
    order: 4,
    title: 'Calculer une image f(0), f(1), f(2)',
    hook: 'On me demande f(2) : je remplace tous les x par 2.',
    mentalImage: 'Une machine ou x entre et un nombre sort.',
    whenToUse: ['Calculer f', 'Verifier que f', 'benefice pour x'],
    method: ['Remplacer x avec des parentheses', 'Calculer ligne par ligne', 'Conclure par une phrase'],
    miniQuiz: [
      { id: 'reflex_4_q1', prompt: 'f(x)=2x+3. f(0) ?', answer: '3', explanation: '2 x 0 + 3 = 3.' },
      { id: 'reflex_4_q2', prompt: 'f(x)=x2-5x+6. f(2) ?', answer: '0', explanation: '4 - 10 + 6 = 0.' },
      { id: 'reflex_4_q3', prompt: 'f(x)=-x2+6x-5. f(1) ?', answer: '0', explanation: '-1 + 6 - 5 = 0.' },
    ],
    magicPhraseId: 'phrase_4',
    qcmPointsCovered: 0.4,
  },
  {
    id: 'reflex_5',
    order: 5,
    title: 'Lecture graphique',
    hook: 'La courbe dit quoi lire. Je n invente rien.',
    mentalImage: 'Un doigt qui monte depuis l axe horizontal jusqu a la courbe.',
    whenToUse: ['image de', 'antecedent de', 'f(x)=0', 'sens de variation'],
    method: ['Image : monter depuis x', 'Antecedent : lire x a la hauteur demandee', 'f(x)=0 : compter les coupes avec l axe horizontal'],
    miniQuiz: [
      { id: 'reflex_5_q1', prompt: 'Image de 2 sur le graphique fourni ?', answer: '3', explanation: 'On lit l ordonnee du point de la courbe.' },
      { id: 'reflex_5_q2', prompt: 'Combien de solutions a f(x)=0 ?', answer: '2', explanation: 'La courbe coupe deux fois l axe horizontal.' },
      { id: 'reflex_5_q3', prompt: 'Entre 0 et 5, la courbe descend. Variation ?', answer: 'decroissante', explanation: 'Quand ca descend, la fonction est decroissante.' },
    ],
    magicPhraseId: 'phrase_7',
    qcmPointsCovered: 0.4,
  },
  {
    id: 'reflex_6',
    order: 6,
    title: 'Equation hyper-simple ax = b',
    hook: '3x = 12 ? x = 12 / 3 = 4.',
    mentalImage: 'Une balance avec une division finale.',
    whenToUse: ['resoudre equation', 'pour quelle valeur', 'ax = b', 'a/x = b'],
    method: ['ax = 0 donne x = 0', 'ax = b donne x = b / a', 'a/x = b donne x = a / b'],
    miniQuiz: [
      { id: 'reflex_6_q1', prompt: '3x = 0. Solution ?', answer: 'x = 0', explanation: 'ax = 0 donne x = 0.' },
      { id: 'reflex_6_q2', prompt: '5x = 25. Solution ?', answer: 'x = 5', explanation: '25 / 5 = 5.' },
      { id: 'reflex_6_q3', prompt: '60/x = 12. Solution ?', answer: 'x = 5', explanation: '60 / 12 = 5.' },
    ],
    magicPhraseId: 'phrase_3',
    qcmPointsCovered: 0.25,
  },
  {
    id: 'reflex_7',
    order: 7,
    title: 'Probabilite simple',
    hook: 'Combien je veux ? Combien il y en a en tout ? Je divise.',
    mentalImage: 'Une cible : zone voulue sur zone totale.',
    whenToUse: ['probabilite', 'tableau croise', 'sachant que'],
    method: ['Cas simple : denominateur = total general', 'Cas conditionnel : denominateur = sous-groupe', 'Case manquante : total - case connue'],
    miniQuiz: [
      { id: 'reflex_7_q1', prompt: '200 personnes, 80 femmes. P(femme) ?', answer: '0,4', explanation: '80 / 200 = 0,4.' },
      { id: 'reflex_7_q2', prompt: 'Parmi 80 femmes, 30 yoga. P(yoga sachant femme) ?', answer: '0,375', explanation: '30 / 80 = 0,375.' },
      { id: 'reflex_7_q3', prompt: 'Total 100, case connue 65. Case manquante ?', answer: '35', explanation: '100 - 65 = 35.' },
    ],
    magicPhraseId: 'phrase_6',
    qcmPointsCovered: 0.25,
  },
];

export function getReflex(id: string): SurvivalReflex | undefined {
  return REFLEXES.find((reflex) => reflex.id === id);
}
