// Client-side enums that mirror Prisma schema enums
// This file contains the same enum values as in prisma/schema.prisma
// but can be safely imported in client components

export enum UserRole {
  ADMIN = 'ADMIN',
  ASSISTANTE = 'ASSISTANTE',
  COACH = 'COACH',
  PARENT = 'PARENT',
  ELEVE = 'ELEVE'
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED'
}

export enum ServiceType {
  COURS_ONLINE = 'COURS_ONLINE',
  COURS_PRESENTIEL = 'COURS_PRESENTIEL',
  ATELIER_GROUPE = 'ATELIER_GROUPE'
}

export enum Subject {
  MATHEMATIQUES = 'MATHEMATIQUES',
  NSI = 'NSI',
  FRANCAIS = 'FRANCAIS',
  PHILOSOPHIE = 'PHILOSOPHIE',
  HISTOIRE_GEO = 'HISTOIRE_GEO',
  ANGLAIS = 'ANGLAIS',
  ESPAGNOL = 'ESPAGNOL',
  PHYSIQUE_CHIMIE = 'PHYSIQUE_CHIMIE',
  SVT = 'SVT',
  SES = 'SES'
}

export enum GradeLevel {
  TROISIEME = 'TROISIEME',
  SECONDE = 'SECONDE',
  PREMIERE = 'PREMIERE',
  TERMINALE = 'TERMINALE',
  POSTBAC = 'POSTBAC',
  AUTRE = 'AUTRE'
}

export enum AcademicTrack {
  COLLEGE = 'COLLEGE',
  EDS_GENERALE = 'EDS_GENERALE',
  STMG = 'STMG',
  STI2D = 'STI2D',
  ST2S = 'ST2S',
  STL = 'STL',
  STD2A = 'STD2A',
  STMG_NON_LYCEEN = 'STMG_NON_LYCEEN'
}

export enum StmgPathway {
  RHC = 'RHC',
  MERCATIQUE = 'MERCATIQUE',
  GF = 'GF',
  SIG = 'SIG',
  INDETERMINE = 'INDETERMINE'
}

export enum SessionStatus {
  SCHEDULED = 'SCHEDULED',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  RESCHEDULED = 'RESCHEDULED'
}

export enum PaymentType {
  SUBSCRIPTION = 'SUBSCRIPTION',
  CREDIT_PACK = 'CREDIT_PACK',
  SPECIAL_PACK = 'SPECIAL_PACK'
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED'
}

// ═══════════════════════════════════════════════════════════════════════════════
// NPC - NEXUS PEDAGOGY COCKPIT ENUMS
// ═══════════════════════════════════════════════════════════════════════════════

export enum CopySubmissionStatus {
  PENDING_UPLOAD = 'PENDING_UPLOAD',
  UPLOADED = 'UPLOADED',
  PROCESSING_OCR = 'PROCESSING_OCR',
  OCR_FAILED = 'OCR_FAILED',
  READY_FOR_AI = 'READY_FOR_AI',
  QUEUED_FOR_ANALYSIS = 'QUEUED_FOR_ANALYSIS',
  ANALYZING = 'ANALYZING',
  ANALYSIS_FAILED = 'ANALYSIS_FAILED',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED'
}

export enum AssessmentSourceType {
  DS = 'DS',
  DM = 'DM',
  BILAN = 'BILAN',
  STAGE = 'STAGE',
  ANNALES = 'ANNALES',
  EXERCICE = 'EXERCICE',
  COMPOSITION = 'COMPOSITION',
  AUTRE = 'AUTRE'
}

export enum CopyPageStatus {
  UPLOADED = 'UPLOADED',
  PENDING_CONVERSION = 'PENDING_CONVERSION',
  CONVERTING = 'CONVERTING',
  CONVERSION_FAILED = 'CONVERSION_FAILED',
  READY = 'READY',
  PROCESSING = 'PROCESSING',
  ERROR = 'ERROR'
}

export enum AiJobType {
  VISION_OCR = 'VISION_OCR',
  PEDAGOGICAL_DIAGNOSIS = 'PEDAGOGICAL_DIAGNOSIS',
  COMPETENCE_MATRIX = 'COMPETENCE_MATRIX',
  REMEDIATION_ROADMAP = 'REMEDIATION_ROADMAP',
  MENTOR_ADVICE = 'MENTOR_ADVICE'
}

export enum AiJobStatus {
  PENDING = 'PENDING',
  QUEUED = 'QUEUED',
  CLAIMED = 'CLAIMED',
  PROCESSING = 'PROCESSING',
  RETRYING = 'RETRYING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}

export enum AiJobPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT'
}

export enum PedagogicalReportStatus {
  DRAFT = 'DRAFT',
  PENDING_VALIDATION = 'PENDING_VALIDATION',
  VALIDATED = 'VALIDATED',
  SENT_TO_STUDENT = 'SENT_TO_STUDENT',
  READ_BY_STUDENT = 'READ_BY_STUDENT',
  ARCHIVED = 'ARCHIVED'
}

export enum ReportVisibility {
  COACH_ONLY = 'COACH_ONLY',
  COACH_AND_STUDENT = 'COACH_AND_STUDENT',
  STUDENT_SUMMARY_ONLY = 'STUDENT_SUMMARY_ONLY'
}

export enum FeedbackType {
  TECHNICAL_ERROR = 'TECHNICAL_ERROR',
  PEDAGOGICAL_INACCURACY = 'PEDAGOGICAL_INACCURACY',
  MISSING_REMEDIATION = 'MISSING_REMEDIATION',
  OVERLY_GENERIC = 'OVERLY_GENERIC',
  STUDENT_MISUNDERSTOOD = 'STUDENT_MISUNDERSTOOD',
  COACH_DISAGREES = 'COACH_DISAGREES',
  POSITIVE = 'POSITIVE',
  OTHER = 'OTHER'
}
