-- CreateEnum
CREATE TYPE "ParcoursType" AS ENUM ('P1_LIBRE_2ANS_MODALITE_A', 'P2_LIBRE_2ANS_MODALITE_B', 'P3_LIBRE_1AN_DEROGATION', 'P4_REDOUBLEMENT_PREMIERE', 'P5_REDOUBLEMENT_TERMINALE', 'P6_AMELIORATION_ET_TERMINALE', 'P7_TITULAIRE_BAC', 'P8_SCOLARISE_VERS_LIBRE', 'P10_EPREUVES_ANTICIPEES_SEULES', 'P11_SECOND_GROUPE', 'P12_ETALEMENT_PLURISESSIONS');

-- AlterTable
ALTER TABLE "profils_candidats" ADD COLUMN "changementSpecialite" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "intentionAmelioration" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "quotes" ADD COLUMN "parcours" "ParcoursType";
