export const SELECTORS = {
  BILAN_FORM: {
    INPUT_PARENT_EMAIL: 'input-parent-email',
    INPUT_PARENT_FIRSTNAME: 'input-parent-firstname',
    INPUT_PARENT_LASTNAME: 'input-parent-lastname',
    INPUT_PARENT_TEL: 'input-parent-tel',
    INPUT_CHILD_FIRSTNAME: 'input-child-firstname',
    SELECT_CHILD_LEVEL: 'select-child-level',
    BTN_NEXT_STEP: 'btn-next-step',
    BTN_SUBMIT: 'btn-submit-bilan',
    ERROR_EMAIL: 'error-parent-email',
    ERROR_GLOBAL: 'form-error-global',
  },
  CONTACT_FORM: {
    INPUT_NOM: 'input-contact-nom',
    INPUT_EMAIL: 'input-contact-email',
    INPUT_MESSAGE: 'input-contact-message',
    BTN_SUBMIT: 'btn-submit-contact',
    SUCCESS_MESSAGE: 'contact-success-message',
  },
  AUTH: {
    INPUT_EMAIL: 'input-email',
    INPUT_PASSWORD: 'input-password',
    BTN_TOGGLE_PASSWORD: 'btn-toggle-password',
    BTN_SIGNIN: 'btn-signin',
  },
  PARENT_DIALOGS: {
    BTN_ADD_CHILD: 'btn-add-child',
    DIALOG_ADD_CHILD: 'dialog-add-child',
    BTN_DIALOG_SUBMIT: 'btn-dialog-submit',
    ERROR_CHILD_FIRSTNAME: 'error-child-firstname',
    BTN_INVOICE_DETAILS: 'btn-invoice-details',
    DIALOG_INVOICE_DETAILS: 'dialog-invoice-details',
    INVOICE_NUMBER: 'invoice-number',
    BTN_DOWNLOAD_INVOICE: 'btn-download-invoice',
    CHILD_SELECTOR: 'child-selector',
    PLACEHOLDER_NO_CHILD: 'placeholder-no-child',
  },
  ADMIN: {
    BTN_CREATE_USER: 'btn-create-user',
    INPUT_SEARCH_USERS: 'input-search-users',
    USERS_TABLE_ROW: 'users-table-row',
    BTN_NEXT_PAGE: 'btn-next-page',
    CURRENT_PAGE: 'current-page',
    BTN_GENERATE_INVOICE: 'btn-generate-invoice',
    BTN_TEST_DB: 'btn-test-db',
    TEST_DB_RESULT: 'test-db-result',
  },
  DOCUMENTS: {
    BTN_UPLOAD: 'btn-upload-document',
    BTN_PREVIEW: 'btn-preview-document',
    BTN_DOWNLOAD: 'btn-download-document',
    ERROR_FILE_TYPE: 'error-file-type',
    ERROR_FILE_SIZE: 'error-file-size',
    PREVIEW_MODAL: 'document-preview-modal',
    PDF_VIEWER: 'pdf-viewer',
  },
  SESSIONS: {
    BTN_JOIN_SESSION: 'btn-join-session',
    BANNER_INSUFFICIENT_CREDITS: 'banner-insufficient-credits',
    BANNER_CREDITS_EXPIRED: 'banner-credits-expired',
  },
  SUBSCRIPTIONS: {
    STATUS: 'subscription-status',
    PLAN: 'subscription-plan',
    BANNER_EXPIRED: 'banner-subscription-expired',
    BTN_RENEW: 'btn-renew-subscription',
    BANNER_PENDING: 'banner-pending-subscription',
    NO_SUBSCRIPTION: 'no-subscription-placeholder',
  },
  NOTIFICATIONS: {
    COUNT_BADGE: 'notifications-count-badge',
    BTN_MARK_READ: 'btn-mark-notification-read',
  },
  ERRORS: {
    PAGE_404_TITLE: 'page-404-title',
    BTN_BACK_HOME: 'btn-back-home',
    ARIA_ERROR: 'aria-error-message',
    SESSIONS_ERROR: 'sessions-loading-error',
    CLICTOPAY_UNAVAILABLE: 'clictopay-unavailable-message',
  },
  NAVBAR: {
    HAMBURGER: 'navbar-hamburger',
    LINKS_DESKTOP: 'navbar-links-desktop',
    MENU_MOBILE: 'navbar-menu-mobile',
    MOBILE_LINK_OFFRES: 'mobile-link-offres',
  },
  ELEVE_DASHBOARD: {
    NEXUS_INDEX_VALUE: 'nexus-index-value',
    BTN_OPEN_ARIA: 'btn-open-aria',
    ARIA_INPUT: 'aria-input',
    BTN_ARIA_SEND: 'btn-aria-send',
  },
  COACH: {
    BTN_ADD_AVAILABILITY: 'btn-add-availability',
    SELECT_DAY_OF_WEEK: 'select-day-of-week',
    INPUT_START_TIME: 'input-start-time',
    INPUT_END_TIME: 'input-end-time',
    TOGGLE_RECURRING: 'toggle-recurring',
    BTN_SAVE_AVAILABILITY: 'btn-save-availability',
  },
  PAYMENTS: {
    BANNER_PENDING: 'banner-pending-payment',
    BTN_DECLARE_TRANSFER: 'btn-declare-transfer',
    BTN_PAY_ONLINE: 'btn-pay-online',
  },
  auth: {
    email: 'input[type="email"]',
    password: 'input[type="password"]',
    submit: 'button[type="submit"]',
  },
  booking: {
    subjectTrigger: 'booking-subject-trigger',
    coachTrigger: 'booking-coach-trigger',
    step1Next: 'booking-step1-next',
    firstSlot: 'booking-slot-0',
  },
  dashboards: {
    parentReady: 'parent-dashboard-ready',
    studentReady: 'student-dashboard-ready',
  },
} as const;
