import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { FamilyForm } from '@/components/dashboard/assistante/FamilyForm';
jest.mock('next/navigation', () => ({ useRouter: () => ({ replace: jest.fn(), refresh: jest.fn() }) }));
it('creates siblings with one phone invitation and no required student email', async () => {
  global.fetch = jest.fn().mockResolvedValue({ ok: true, json: async () => ({ children: [{ studentId: 's1' }, { studentId: 's2' }], invitationQueued: true }) });
  render(<FamilyForm mode="WHATSAPP" />);
  fireEvent.change(screen.getByLabelText('Prénom du parent'), { target: { value: 'Claire' } });
  fireEvent.change(screen.getByLabelText('Nom du parent'), { target: { value: 'Test' } });
  fireEvent.change(screen.getByLabelText('Téléphone du parent'), { target: { value: '+216 99192829' } });
  fireEvent.change(screen.getByLabelText('Prénom de l’enfant'), { target: { value: 'Nora' } });
  fireEvent.change(screen.getByLabelText('Nom de l’enfant'), { target: { value: 'Distinct' } });
  fireEvent.change(screen.getByLabelText('Situation scolaire'), { target: { value: 'INDIVIDUAL' } });
  fireEvent.change(screen.getByLabelText('Niveau'), { target: { value: 'Première' } });
  expect(screen.queryByLabelText('Objectif déclaré')).not.toBeInTheDocument();
  expect(screen.getByText(/Le projet bac sera renseigné dans le dossier candidat/)).toBeInTheDocument();
  fireEvent.change(screen.getByLabelText('Niveau'), { target: { value: 'Terminale' } });
  fireEvent.click(screen.getByRole('button', { name: 'Ajouter un enfant' }));
  fireEvent.change(screen.getAllByLabelText('Prénom de l’enfant')[1], { target: { value: 'Ali' } });
  fireEvent.change(screen.getAllByLabelText('Nom de l’enfant')[1], { target: { value: 'Autre' } });
  fireEvent.click(screen.getByRole('button', { name: 'Créer le foyer et continuer' }));
  expect(await screen.findByText('Foyer enregistré')).toBeInTheDocument();
  await waitFor(() => expect(global.fetch).toHaveBeenCalledTimes(1));
  const [url, request] = (global.fetch as jest.Mock).mock.calls[0];
  expect(url).toBe('/api/assistante/families');
  expect(request.headers['idempotency-key']).toMatch(/^foyer-/);
  expect(JSON.parse(request.body)).toMatchObject({ parentPhone: '+216 99192829', children: [{ firstName: 'Nora', lastName: 'Distinct', schoolingStatus: 'INDIVIDUAL' }, { firstName: 'Ali', lastName: 'Autre' }] });
  expect(JSON.parse(request.body)).not.toHaveProperty('parentEmail');
  expect(JSON.parse(request.body).children[0]).not.toHaveProperty('candidateProfile');
  expect(screen.getByText(/mise en file ne confirme pas/)).toBeInTheDocument();
  expect(screen.getByRole('link', { name: 'Compléter le dossier candidat de Nora' })).toHaveAttribute('href', '/dashboard/assistante/students/s1/candidat');
});
