import {
  curriculumVersionSchema,
  type CurriculumVersion,
} from '../schemas/curriculum';

const BO_2026_SECONDE = {
  id: 'bo-2026-14-mene2602914a',
  authority: 'MEN' as const,
  title: 'Programme de mathématiques de la classe de seconde générale et technologique',
  uri: 'https://www.education.gouv.fr/bo/2026/Hebdo14/MENE2602914A',
  publicationDate: '2026-04-02',
  bulletinReference: 'BO n° 14 du 2 avril 2026',
};

const RAW_MATHEMATICS_CURRICULA: CurriculumVersion[] = [
  {
    id: 'fr-maths-troisieme-cycle4-2020',
    version: '2020.1',
    status: 'PUBLISHED',
    subject: 'MATHEMATICS',
    level: 'TROISIEME',
    track: 'COLLEGE',
    subjectVariant: 'COMMON',
    effectiveFromAcademicYear: '2020-2021',
    effectiveToAcademicYear: '2027-2028',
    officialSources: [{
      id: 'eduscol-cycle4-maths-2020',
      authority: 'EDUSCOL',
      title: 'Programme du cycle 4 en vigueur en classe de troisième en 2025-2026',
      uri: 'https://eduscol.education.gouv.fr/media/67722/download',
      publicationDate: '2020-07-30',
      bulletinReference: 'BO n° 31 du 30 juillet 2020',
    }],
  },
  {
    id: 'fr-maths-troisieme-cycle4-2026',
    version: '2026.1',
    status: 'PUBLISHED',
    subject: 'MATHEMATICS',
    level: 'TROISIEME',
    track: 'COLLEGE',
    subjectVariant: 'COMMON',
    effectiveFromAcademicYear: '2028-2029',
    officialSources: [{
      id: 'bo-2026-10-cycle4-maths',
      authority: 'MEN',
      title: 'Programme de mathématiques pour le cycle 4',
      uri: 'https://www.education.gouv.fr/sites/default/files/document/Bulletin%20officiel%20n%C2%B0%2010%20du%205%20mars%202026-480833.pdf',
      publicationDate: '2026-03-05',
      bulletinReference: 'BO n° 10 du 5 mars 2026',
    }],
  },
  {
    id: 'fr-maths-seconde-gt-2019',
    version: '2019.1',
    status: 'PUBLISHED',
    subject: 'MATHEMATICS',
    level: 'SECONDE',
    track: 'GENERAL_TECHNOLOGICAL',
    subjectVariant: 'COMMON',
    effectiveFromAcademicYear: '2019-2020',
    effectiveToAcademicYear: '2025-2026',
    officialSources: [{
      id: 'bo-special-2019-1-maths-seconde',
      authority: 'EDUSCOL',
      title: 'Programme de mathématiques de seconde générale et technologique',
      uri: 'https://eduscol.education.gouv.fr/sites/default/files/document/spe631annexe1062957pdf-84144.pdf',
      publicationDate: '2019-01-22',
      bulletinReference: 'BO spécial n° 1 du 22 janvier 2019',
    }],
  },
  {
    id: 'fr-maths-seconde-gt-2026',
    version: '2026.1',
    status: 'PUBLISHED',
    subject: 'MATHEMATICS',
    level: 'SECONDE',
    track: 'GENERAL_TECHNOLOGICAL',
    subjectVariant: 'COMMON',
    effectiveFromAcademicYear: '2026-2027',
    officialSources: [BO_2026_SECONDE],
  },
  {
    id: 'fr-maths-premiere-speciality-2019',
    version: '2019.1',
    status: 'PUBLISHED',
    subject: 'MATHEMATICS',
    level: 'PREMIERE',
    track: 'GENERAL',
    subjectVariant: 'SPECIALITY',
    effectiveFromAcademicYear: '2019-2020',
    effectiveToAcademicYear: '2025-2026',
    officialSources: [{
      id: 'bo-special-2019-1-maths-premiere-speciality',
      authority: 'EDUSCOL',
      title: 'Programme de spécialité mathématiques de première générale',
      uri: 'https://eduscol.education.gouv.fr/sites/default/files/document/spe632annexe1063168pdf-84156.pdf',
      publicationDate: '2019-01-22',
      bulletinReference: 'BO spécial n° 1 du 22 janvier 2019',
    }],
  },
  {
    id: 'fr-maths-premiere-speciality-2026',
    version: '2026.1',
    status: 'PUBLISHED',
    subject: 'MATHEMATICS',
    level: 'PREMIERE',
    track: 'GENERAL',
    subjectVariant: 'SPECIALITY',
    effectiveFromAcademicYear: '2026-2027',
    officialSources: [{
      id: 'bo-2026-14-maths-premiere-speciality',
      authority: 'MEN',
      title: 'Programme de spécialité mathématiques de première de la voie générale',
      uri: 'https://www.education.gouv.fr/sites/default/files/document/Annexe%20%E2%80%93%20Programme%20d%26%23039%3Benseignement%20de%20sp%C3%A9cialit%C3%A9%20de%20math%C3%A9matiques%20de%20la%20classe%20de%20premi%C3%A8re%20de%20la%20voie%20g%C3%A9n%C3%A9rale-515408.pdf',
      publicationDate: '2026-04-02',
      bulletinReference: 'BO n° 14 du 2 avril 2026',
    }],
  },
  {
    id: 'fr-maths-terminale-speciality-2019',
    version: '2019.1',
    status: 'PUBLISHED',
    subject: 'MATHEMATICS',
    level: 'TERMINALE',
    track: 'GENERAL',
    subjectVariant: 'SPECIALITY',
    effectiveFromAcademicYear: '2020-2021',
    effectiveToAcademicYear: '2026-2027',
    officialSources: [{
      id: 'bo-special-2019-8-maths-terminale-speciality',
      authority: 'EDUSCOL',
      title: 'Programme de spécialité mathématiques de terminale générale',
      uri: 'https://eduscol.education.gouv.fr/sites/default/files/document/spe246annexe1158907pdf-84159.pdf',
      publicationDate: '2019-07-25',
      bulletinReference: 'BO spécial n° 8 du 25 juillet 2019',
    }],
  },
  {
    id: 'fr-maths-terminale-speciality-2026',
    version: '2026.1',
    status: 'PUBLISHED',
    subject: 'MATHEMATICS',
    level: 'TERMINALE',
    track: 'GENERAL',
    subjectVariant: 'SPECIALITY',
    effectiveFromAcademicYear: '2027-2028',
    officialSources: [{
      id: 'bo-2026-14-maths-terminale-speciality',
      authority: 'MEN',
      title: 'Programme de spécialité mathématiques de terminale de la voie générale',
      uri: 'https://www.education.gouv.fr/sites/default/files/document/Annexe%20%E2%80%93%20Programme%20de%20l%26%23039%3Benseignement%20de%20sp%C3%A9cialit%C3%A9%20de%20math%C3%A9matiques%20de%20la%20classe%20terminale%20de%20la%20voie%20g%C3%A9n%C3%A9rale-515414.pdf',
      publicationDate: '2026-04-02',
      bulletinReference: 'BO n° 14 du 2 avril 2026',
    }],
  },
];

export const MATHEMATICS_CURRICULA: readonly CurriculumVersion[] = Object.freeze(
  RAW_MATHEMATICS_CURRICULA.map((curriculum) => curriculumVersionSchema.parse(curriculum)),
);
