/**
 * Client-safe pricing accessors — lightweight subset of pricing.canonical.json.
 *
 * This module is safe to import in 'use client' components: it loads only
 * two generated JSON files (~2.7 KB total) instead of the full 28 KB canonical.
 *
 * Data files are generated by: node scripts/generate-pricing-client-data.js
 * Run that script after editing pricing.canonical.json.
 *
 * lib/pricing.ts (server-only) remains the authoritative accessor for the
 * full canonical data. A sync test (__tests__/lib/pricing-client-sync.test.ts)
 * ensures the generated files stay aligned.
 */

import type { Rules } from './pricing';
import clientData from '@/data/pricing-client-data.generated.json';
import stageCalendarMini from '@/data/stage-calendar-client.json';

// ── Typed re-exports from generated JSON ──

export const PRICING_RULES = clientData.rules as unknown as Rules;
export const PRICING_REPERES = clientData.reperes_tarifaires;
export const PRICING_ANNUAL_OFFER_SUMMARIES = clientData.annual_offer_summaries;
export type AnnualOfferPricingSummary = (typeof PRICING_ANNUAL_OFFER_SUMMARIES)[number];

// ── Client-safe accessors ──

export function getRules(): Rules {
  return PRICING_RULES;
}

export function getReperes(): typeof PRICING_REPERES {
  return PRICING_REPERES;
}

export function getAnnualOfferPricing(id: string): AnnualOfferPricingSummary | undefined {
  return PRICING_ANNUAL_OFFER_SUMMARIES.find((offer) => offer.id === id);
}

export function getNextStage(referenceDate?: Date): { title: string; dates_display: string; date_start: string } | null {
  const now = referenceDate ?? new Date();
  // Compare YYYY-MM-DD strings to avoid UTC-vs-local timezone skew entirely.
  const todayStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
  const upcoming = (stageCalendarMini as Array<{ title: string; date_start: string; dates_display: string }>)
    .filter((e) => e.date_start >= todayStr)
    .sort((a, b) => a.date_start.localeCompare(b.date_start));
  if (upcoming.length === 0) return null;
  const next = upcoming[0];
  return { title: next.title, dates_display: next.dates_display, date_start: next.date_start };
}
