/**
 * ARIA_PARENT_MASTERY_GOLDEN_E2E (P6c) / PARENT_REPORTING_E2E (P7a) — the
 * real parent journey P6a/P6b/P7a built but never exercised end to end in
 * a real browser: parent login -> own child -> ARIA mastery card -> real
 * course -> real mastery, Next Best Action and recent-activity feed
 * generated by the child's real practice.
 *
 * Two real, independent browser identities in one test (a real parent and
 * their real child never share a session): the child's real practice
 * attempt is driven through the real authenticated `/api/aria/practice/**`
 * endpoints (the UI walk-through for that exact journey is
 * practice.spec.ts's own job, not duplicated here), then a genuinely
 * separate parent session verifies the real cross-family-isolated
 * `/api/parent/children/[studentId]/aria/**` read paths render it — never
 * the child's private chat, which this journey never touches.
 */
import { expect, test } from '@playwright/test';
import { CREDS } from '../helpers/credentials';
import { loginAsUser } from '../helpers/auth';
import { authorRealAriaPracticeActivity, cleanupAriaPracticeGoldenPath, getStudentId } from '../helpers/db';
import { resetFixture } from './helpers';

const REAL_COURSE_KEY = 'eds-maths-premiere';
const REAL_SKILL_ID = 'ALG_SUITE_ARITH';
const REAL_SKILL_LABEL = 'Suites arithmétiques (u_n, somme)';

const MCQ_PROMPT = Object.freeze({
  questionText: 'Quelle est la raison de la suite arithmétique (u_n) définie par u_n = 3n + 1 ?',
  options: [
    { id: 'a', label: '3' },
    { id: 'b', label: '1' },
  ],
});
const MCQ_EXPECTED_ANSWER_SHAPE = Object.freeze({ field: 'selectedOptionId', type: 'string' });
const MCQ_CORRECTION_RUBRIC = Object.freeze({ correctOptionId: 'a' });

test.describe.serial('ARIA-P6c real parent Mastery golden path', () => {
  test.beforeEach(async ({ request }) => {
    await cleanupAriaPracticeGoldenPath(REAL_COURSE_KEY);
    await resetFixture(request);
  });

  test.afterAll(async () => {
    await cleanupAriaPracticeGoldenPath(REAL_COURSE_KEY);
  });

  test('E2E_ARIA_PARENT_MASTERY_GOLDEN — real parent sees real mastery generated by the real child\'s real practice', async ({ browser }) => {
    const activity = await authorRealAriaPracticeActivity({
      courseKey: REAL_COURSE_KEY,
      skillId: REAL_SKILL_ID,
      curriculumVersion: '2026-v1',
      prompt: MCQ_PROMPT,
      expectedAnswerShape: MCQ_EXPECTED_ANSWER_SHAPE,
      correctionRubric: MCQ_CORRECTION_RUBRIC,
    });

    // ── Real child session: drive a real submit -> correct through the
    // real authenticated API (the full UI walk-through is practice.spec.ts's job).
    const studentContext = await browser.newContext();
    const studentPage = await studentContext.newPage();
    await loginAsUser(studentPage, 'ariaPremiereMaths');

    const startResponse = await studentPage.request.post('/api/aria/practice/attempts', {
      data: { activityId: activity.activityId },
    });
    expect(startResponse.status()).toBe(200);
    const { attempt } = (await startResponse.json()) as { attempt: { id: string } };

    const submitResponse = await studentPage.request.post(`/api/aria/practice/attempts/${attempt.id}/submit`, {
      data: { payload: { selectedOptionId: 'a' } },
    });
    expect(submitResponse.status()).toBe(200);

    const correctResponse = await studentPage.request.post(`/api/aria/practice/attempts/${attempt.id}/correct`);
    expect(correctResponse.status()).toBe(200);
    const { result } = (await correctResponse.json()) as { result: { outcome: string } };
    expect(result.outcome).toBe('CORRECT');
    await studentContext.close();

    // ── Real, genuinely separate parent session.
    const studentId = await getStudentId(CREDS.ariaPremiereMaths.email);
    const parentContext = await browser.newContext();
    const parentPage = await parentContext.newPage();
    // 'parent' is a different, unrelated seed fixture with her own,
    // disjoint children — the real parent of every ARIA E2E persona
    // (including ariaPremiereMaths) is 'ariaPersonasParent' (see
    // scripts/seed-e2e-db.ts's credentials manifest).
    await loginAsUser(parentPage, 'ariaPersonasParent');
    await parentPage.goto(`/dashboard/parent/enfant/${studentId}`, { waitUntil: 'domcontentloaded' });

    const masteryCard = parentPage.getByTestId('aria-mastery-card');
    await expect(masteryCard).toBeVisible();
    await expect(masteryCard).toContainText(REAL_SKILL_LABEL);
    await expect(masteryCard).toContainText('En progrès');

    // P7a: the real Next Best Action recommendation and recent-activity
    // feed, generated from the same real correction above — never the
    // child's private chat, which this card never fetches.
    const parentNba = parentPage.getByTestId('aria-parent-next-best-action');
    await expect(parentNba).toBeVisible();
    await expect(parentNba).toContainText(REAL_SKILL_LABEL);

    const parentRecentActivity = parentPage.getByTestId('aria-parent-recent-activity');
    await expect(parentRecentActivity).toBeVisible();
    await expect(parentRecentActivity).toContainText(REAL_SKILL_LABEL);
    await expect(parentRecentActivity).toContainText('Correct');

    await parentContext.close();
  });

  // Real cross-family isolation (a second real parent+child pair, verified
  // with a real 403) is already covered by the P6a DB test suite
  // (__tests__/db/aria-parent-course-mastery.real.test.ts) — no second
  // `parent`-role E2E credential exists to duplicate that here without
  // widening the seed. This test instead covers the real role gate itself
  // through a genuine authenticated round trip, which the DB suite (it
  // calls the application function directly, bypassing the route) does not.
  test('rejects a real, authenticated non-PARENT session hitting the parent-only mastery route', async ({ browser }) => {
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();
    await loginAsUser(adminPage, 'admin');
    const studentId = await getStudentId(CREDS.ariaPremiereMaths.email);
    const response = await adminPage.request.get(
      `/api/parent/children/${studentId}/aria/mastery?courseKey=${REAL_COURSE_KEY}`,
    );
    expect(response.status()).toBe(401);
    await adminContext.close();
  });
});
