import type { Domain, Chapter, QcmQuestion, OpenQuestion, DiscoveryCluster } from './types';

export const DOMAINS: Domain[] = [
  { id: 'D1', title: 'Analyse', order: 1 },
  { id: 'D2', title: 'Algèbre et géométrie', order: 2 },
  { id: 'D3', title: 'Probabilités', order: 3 },
  { id: 'D4', title: 'Algorithmique et programmation', order: 4 },
  { id: 'D5', title: 'Logique et raisonnement', order: 5 },
];

export const CHAPTERS: Chapter[] = [
  { id: 'C1', domainId: 'D1', title: 'Suites et limites de suites', bacPriority: 5, isCore: true },
  { id: 'C2', domainId: 'D1', title: 'Raisonnement par récurrence', bacPriority: 5, isCore: true },
  { id: 'C3', domainId: 'D1', title: 'Limites de fonctions', bacPriority: 5, isCore: true },
  { id: 'C4', domainId: 'D1', title: 'Compléments de dérivation', bacPriority: 5, isCore: true },
  { id: 'C5', domainId: 'D1', title: 'Fonctions composées', bacPriority: 4, isCore: true },
  { id: 'C6', domainId: 'D1', title: 'Convexité et dérivée seconde', bacPriority: 4, isCore: false },
  { id: 'C7', domainId: 'D1', title: 'Continuité et TVI', bacPriority: 5, isCore: true },
  { id: 'C8', domainId: 'D1', title: 'Fonction logarithme népérien', bacPriority: 5, isCore: true },
  { id: 'C9', domainId: 'D1', title: 'Fonctions sinus et cosinus', bacPriority: 3, isCore: false },
  { id: 'C10', domainId: 'D1', title: 'Primitives', bacPriority: 5, isCore: true },
  { id: 'C11', domainId: 'D1', title: 'Équations différentielles', bacPriority: 4, isCore: false },
  { id: 'C12', domainId: 'D1', title: 'Calcul intégral', bacPriority: 5, isCore: true },
  { id: 'C13', domainId: 'D1', title: 'Intégration par parties', bacPriority: 4, isCore: false },
  { id: 'C14', domainId: 'D1', title: "Valeur moyenne d'une fonction", bacPriority: 4, isCore: false },
  { id: 'C15', domainId: 'D2', title: 'Combinatoire et dénombrement', bacPriority: 4, isCore: false },
  { id: 'C16', domainId: 'D2', title: "Vecteurs de l'espace", bacPriority: 4, isCore: true },
  { id: 'C17', domainId: 'D2', title: "Droites et plans de l'espace", bacPriority: 5, isCore: true },
  { id: 'C18', domainId: 'D2', title: "Bases et repères de l'espace", bacPriority: 3, isCore: false },
  { id: 'C19', domainId: 'D2', title: "Produit scalaire dans l'espace", bacPriority: 5, isCore: true },
  { id: 'C20', domainId: 'D2', title: "Orthogonalité dans l'espace", bacPriority: 5, isCore: true },
  { id: 'C21', domainId: 'D2', title: 'Vecteur normal à un plan', bacPriority: 5, isCore: true },
  { id: 'C22', domainId: 'D2', title: "Représentation paramétrique d'une droite", bacPriority: 5, isCore: true },
  { id: 'C23', domainId: 'D2', title: "Équation cartésienne d'un plan", bacPriority: 5, isCore: true },
  { id: 'C24', domainId: 'D2', title: 'Projeté orthogonal', bacPriority: 4, isCore: false },
  { id: 'C25', domainId: 'D2', title: "Distance d'un point", bacPriority: 3, isCore: false },
  { id: 'C26', domainId: 'D2', title: "Positions relatives dans l'espace", bacPriority: 4, isCore: false },
  { id: 'C27', domainId: 'D3', title: "Succession d'épreuves indépendantes", bacPriority: 4, isCore: false },
  { id: 'C28', domainId: 'D3', title: 'Épreuve et schéma de Bernoulli', bacPriority: 5, isCore: true },
  { id: 'C29', domainId: 'D3', title: 'Loi binomiale', bacPriority: 5, isCore: true },
  { id: 'C30', domainId: 'D3', title: 'Probabilités conditionnelles et arbres', bacPriority: 5, isCore: true },
  { id: 'C31', domainId: 'D3', title: 'Variables aléatoires', bacPriority: 4, isCore: true },
  { id: 'C32', domainId: 'D3', title: 'Espérance, variance, écart-type', bacPriority: 5, isCore: true },
  { id: 'C33', domainId: 'D3', title: 'Somme de variables aléatoires', bacPriority: 3, isCore: false },
  { id: 'C34', domainId: 'D3', title: "Échantillon, moyenne d'échantillon", bacPriority: 2, isCore: false },
  { id: 'C35', domainId: 'D3', title: 'Inégalité de Bienaymé-Tchebychev', bacPriority: 3, isCore: false },
  { id: 'C36', domainId: 'D3', title: 'Loi des grands nombres', bacPriority: 2, isCore: false },
  { id: 'C37', domainId: 'D4', title: 'Variables et affectation', bacPriority: 3, isCore: false },
  { id: 'C38', domainId: 'D4', title: 'Boucles while et for', bacPriority: 4, isCore: true },
  { id: 'C39', domainId: 'D4', title: 'Fonctions Python', bacPriority: 4, isCore: true },
  { id: 'C40', domainId: 'D4', title: 'Listes et compréhension', bacPriority: 3, isCore: false },
  { id: 'C41', domainId: 'D4', title: 'Algorithmes de seuil', bacPriority: 5, isCore: true },
  { id: 'C42', domainId: 'D4', title: 'Dichotomie', bacPriority: 4, isCore: false },
  { id: 'C43', domainId: 'D4', title: "Méthode d'Euler", bacPriority: 2, isCore: false },
  { id: 'C44', domainId: 'D4', title: 'Simulation probabiliste', bacPriority: 3, isCore: false },
  { id: 'C45', domainId: 'D5', title: 'Proposition mathématique', bacPriority: 2, isCore: false },
  { id: 'C46', domainId: 'D5', title: 'Implication, réciproque, contraposée', bacPriority: 3, isCore: false },
  { id: 'C47', domainId: 'D5', title: 'Quantificateurs', bacPriority: 3, isCore: false },
  { id: 'C48', domainId: 'D5', title: 'Négation', bacPriority: 3, isCore: false },
  { id: 'C49', domainId: 'D5', title: 'Contre-exemple', bacPriority: 4, isCore: true },
  { id: 'C50', domainId: 'D5', title: 'Raisonnement par disjonction de cas', bacPriority: 4, isCore: true },
  { id: 'C51', domainId: 'D5', title: "Raisonnement par l'absurde", bacPriority: 4, isCore: true },
  { id: 'C52', domainId: 'D5', title: 'Rédaction mathématique', bacPriority: 5, isCore: true },
];

export const QUESTIONS_QCM: QcmQuestion[] = [
  { id: 'Q1', chapterId: 'C1', skillType: 'méthode', difficulty: 1, bacPriority: 5, skillTag: 'limite_poly', statement: "Soit $u_n = 3n^2 - 5n + 1$. Lorsque $n$ tend vers $+\\infty$, la suite $(u_n)$ :", choices: ["tend vers $-\\infty$", "tend vers $0$", "tend vers $+\\infty$", "converge vers $1$"], correct: 2, explanation: "Le terme dominant est $3n^2$, positif, donc la limite est $+\\infty$." },
  { id: 'Q2', chapterId: 'C1', skillType: 'automatisme', difficulty: 1, bacPriority: 5, skillTag: 'limite_geom', statement: "La suite géométrique $u_n = 5(1/2)^n$ :", choices: ["tend vers $+\\infty$", "tend vers $5$", "tend vers $0$", "n'a pas de limite"], correct: 2, explanation: "La raison est comprise entre -1 et 1, donc la limite est 0." },
  { id: 'Q3', chapterId: 'C2', skillType: 'méthode', difficulty: 2, bacPriority: 5, skillTag: 'recurrence_structure', statement: "Pour démontrer par récurrence une propriété $P(n)$, il faut :", choices: ["vérifier $P(0)$", "montrer $P(n) \\implies P(n+1)$", "vérifier initialisation et hérédité", "calculer les 10 premiers termes"], correct: 2, explanation: "Une récurrence nécessite l'initialisation, l'hérédité et une conclusion." },
  { id: 'Q4', chapterId: 'C1', skillType: 'raisonnement', difficulty: 2, bacPriority: 5, skillTag: 'convergence_monotone', statement: "Si une suite est croissante et majorée, alors :", choices: ["elle diverge vers $+\\infty$", "elle converge", "elle est constante", "elle tend vers $0$"], correct: 1, explanation: "Théorème de convergence monotone." },
  { id: 'Q5', chapterId: 'C1', skillType: 'méthode', difficulty: 2, bacPriority: 5, skillTag: 'theoreme_gendarmes', statement: "Le théorème des gendarmes s'applique pour :", choices: ["trouver la dérivée", "démontrer qu'une suite converge en l'encadrant", "calculer une intégrale", "trouver une primitive"], correct: 1, explanation: "Il permet de trouver la limite d'une suite encadrée par deux suites de même limite." },
  { id: 'Q6', chapterId: 'C2', skillType: 'rédaction', difficulty: 2, bacPriority: 5, skillTag: 'recurrence_heredite', statement: "L'hérédité d'une récurrence consiste à supposer $P(k)$ vraie et montrer que :", choices: ["$P(0)$ est vraie", "$P(k+1)$ est vraie", "$P(k-1)$ est vraie", "la suite est majorée"], correct: 1, explanation: "C'est la définition de l'étape d'hérédité." },
  { id: 'Q7', chapterId: 'C3', skillType: 'méthode', difficulty: 2, bacPriority: 5, skillTag: 'limite_rationnelle', statement: "Limite quand $x$ tend vers $+\\infty$ de $\\frac{3x^2 - 1}{x^2 + 5}$ :", choices: ["$0$", "$1$", "$3$", "$+\\infty$"], correct: 2, explanation: "On factorise par le terme de plus haut degré ou on utilise la règle des termes dominants." },
  { id: 'Q8', chapterId: 'C3', skillType: 'automatisme', difficulty: 2, bacPriority: 5, skillTag: 'croissance_comparee', statement: "Limite quand $x$ tend vers $+\\infty$ de $\\frac{e^x}{x^3}$ :", choices: ["$0$", "$1$", "$+\\infty$", "$3$"], correct: 2, explanation: "Croissances comparées : l'exponentielle l'emporte." },
  { id: 'Q9', chapterId: 'C5', skillType: 'automatisme', difficulty: 2, bacPriority: 4, skillTag: 'derivee_composee', statement: "Si $f(x)=e^{2x+1}$, alors $f'(x)$ vaut :", choices: ["$e^{2x+1}$", "$2e^{2x+1}$", "$(2x+1)e^{2x+1}$", "$e^2$"], correct: 1, explanation: "La dérivée de $e^{u}$ est $u'e^{u}$." },
  { id: 'Q10', chapterId: 'C6', skillType: 'méthode', difficulty: 2, bacPriority: 4, skillTag: 'convexite_derivee_seconde', statement: "Une fonction deux fois dérivable est convexe sur un intervalle si :", choices: ["$f'(x) \\le 0$", "$f''(x) \\ge 0$", "$f(x) \\ge 0$", "$f''(x)=0$"], correct: 1, explanation: "La positivité de la dérivée seconde est la condition de convexité." },
  { id: 'Q11', chapterId: 'C4', skillType: 'automatisme', difficulty: 1, bacPriority: 5, skillTag: 'derivee_quotient', statement: "La dérivée de $\\frac{u}{v}$ est :", choices: ["$\\frac{u'}{v'}$", "$\\frac{u'v - uv'}{v^2}$", "$\\frac{u'v + uv'}{v^2}$", "$u'v'$"], correct: 1, explanation: "Formule classique de dérivation d'un quotient." },
  { id: 'Q12', chapterId: 'C6', skillType: 'raisonnement', difficulty: 2, bacPriority: 4, skillTag: 'point_inflexion', statement: "Un point d'inflexion est atteint lorsque :", choices: ["$f(x)$ s'annule", "$f'(x)$ change de signe", "$f''(x)$ s'annule en changeant de signe", "$f(x)$ atteint un maximum"], correct: 2, explanation: "Un changement de convexité équivaut à un changement de signe de la dérivée seconde." },
  { id: 'Q13', chapterId: 'C8', skillType: 'automatisme', difficulty: 1, bacPriority: 5, skillTag: 'derivee_ln', statement: "Si $f(x)=\\ln(x)$, alors $f'(x)$ vaut :", choices: ["$x$", "$\\ln(x)$", "$\\frac{1}{x}$", "$e^x$"], correct: 2, explanation: "Dérivée usuelle du logarithme." },
  { id: 'Q14', chapterId: 'C8', skillType: 'automatisme', difficulty: 1, bacPriority: 5, skillTag: 'prop_ln', statement: "Pour $a>0$ et $b>0$, $\\ln(ab) =$ ", choices: ["$\\ln(a)+\\ln(b)$", "$\\ln(a)\\ln(b)$", "$\\ln(a-b)$", "$a \\ln(b)$"], correct: 0, explanation: "Propriété algébrique fondamentale du ln." },
  { id: 'Q15', chapterId: 'C8', skillType: 'méthode', difficulty: 2, bacPriority: 5, skillTag: 'croissance_comparee_ln', statement: "Limite quand $x$ tend vers $+\\infty$ de $\\frac{\\ln(x)}{x}$ :", choices: ["$+\\infty$", "$1$", "$0$", "$-\\infty$"], correct: 2, explanation: "Croissances comparées : $x$ l'emporte sur $\\ln(x)$." },
  { id: 'Q16', chapterId: 'C7', skillType: 'raisonnement', difficulty: 3, bacPriority: 5, skillTag: 'tvi_unicite', statement: "Le Corollaire du TVI (TVI monotonie stricte) garantit :", choices: ["une infinité de solutions", "exactement une solution à $f(x)=k$", "que $f$ est dérivable", "que $f$ est convexe"], correct: 1, explanation: "L'ajout de la monotonie stricte assure l'unicité de la solution." },
  { id: 'Q17', chapterId: 'C9', skillType: 'automatisme', difficulty: 1, bacPriority: 3, skillTag: 'derivee_cos', statement: "La dérivée de $\\cos(x)$ est :", choices: ["$\\sin(x)$", "$-\\sin(x)$", "$\\cos(x)$", "$-\\cos(x)$"], correct: 1, explanation: "Rappel des dérivées trigonométriques." },
  { id: 'Q18', chapterId: 'C7', skillType: 'méthode', difficulty: 2, bacPriority: 5, skillTag: 'tvi_conditions', statement: "Pour appliquer le TVI, la fonction $f$ doit absolument être :", choices: ["dérivable", "convexe", "continue", "positive"], correct: 2, explanation: "La continuité est la condition sine qua non du TVI." },
  { id: 'Q19', chapterId: 'C10', skillType: 'automatisme', difficulty: 1, bacPriority: 5, skillTag: 'primitive_poly', statement: "Une primitive de $x^2$ est :", choices: ["$2x$", "$\\frac{x^3}{3}$", "$x^3$", "$\\ln(x)$"], correct: 1, explanation: "En dérivant $x^3/3$, on retombe sur $x^2$." },
  { id: 'Q20', chapterId: 'C12', skillType: 'méthode', difficulty: 2, bacPriority: 5, skillTag: 'calcul_integrale', statement: "L'intégrale $\\int_0^1 2x \\, dx$ vaut :", choices: ["$0$", "$1$", "$2$", "$1/2$"], correct: 1, explanation: "Une primitive est $x^2$, et $1^2 - 0^2 = 1$." },
  { id: 'Q21', chapterId: 'C10', skillType: 'méthode', difficulty: 2, bacPriority: 5, skillTag: 'primitive_composee', statement: "Une primitive de $u'e^u$ est :", choices: ["$e^u$", "$u e^u$", "$e^{u'}$", "$u' e^u$"], correct: 0, explanation: "La dérivée de $e^u$ est $u'e^u$." },
  { id: 'Q22', chapterId: 'C11', skillType: 'automatisme', difficulty: 2, bacPriority: 4, skillTag: 'equa_diff', statement: "Les solutions de l'équation différentielle $y' = ay$ sont de la forme :", choices: ["$ax + b$", "$C e^{ax}$", "$\\ln(ax)$", "$C a^x$"], correct: 1, explanation: "Cours sur les EDO linéaires d'ordre 1." },
  { id: 'Q23', chapterId: 'C14', skillType: 'automatisme', difficulty: 2, bacPriority: 4, skillTag: 'valeur_moyenne', statement: "La valeur moyenne de $f$ sur $[a;b]$ se calcule par :", choices: ["$f(b)-f(a)$", "$\\frac{1}{b-a} \\int_a^b f(x)dx$", "$\\int_a^b f(x)dx$", "$f(\\frac{a+b}{2})$"], correct: 1, explanation: "Formule de la valeur moyenne." },
  { id: 'Q24', chapterId: 'C13', skillType: 'raisonnement', difficulty: 3, bacPriority: 4, skillTag: 'ipp_origine', statement: "L'intégration par parties provient de la formule de dérivation de :", choices: ["$u+v$", "$u/v$", "$u \\times v$", "$u(v)$"], correct: 2, explanation: "C'est l'intégration de la formule $(uv)' = u'v + uv'$." },
  { id: 'Q25', chapterId: 'C29', skillType: 'modélisation', difficulty: 2, bacPriority: 5, skillTag: 'loi_binomiale_def', statement: "Dans un schéma de Bernoulli, la variable comptant le nombre de succès suit :", choices: ["une loi uniforme", "une loi binomiale", "une loi exponentielle", "une loi normale"], correct: 1, explanation: "Définition même de la loi binomiale." },
  { id: 'Q26', chapterId: 'C32', skillType: 'automatisme', difficulty: 1, bacPriority: 5, skillTag: 'esperance_binomiale', statement: "Si $X$ suit une loi $B(n,p)$, alors l'espérance $E(X) =$ :", choices: ["$p$", "$n+p$", "$np$", "$np(1-p)$"], correct: 2, explanation: "Formule du cours." },
  { id: 'Q27', chapterId: 'C15', skillType: 'automatisme', difficulty: 2, bacPriority: 4, skillTag: 'combinaisons', statement: "Le nombre de combinaisons de 3 éléments parmi 10 se note :", choices: ["$10^3$", "$3^{10}$", "$\\binom{10}{3}$", "$10!$"], correct: 2, explanation: "C'est le coefficient binomial." },
  { id: 'Q28', chapterId: 'C30', skillType: 'méthode', difficulty: 2, bacPriority: 5, skillTag: 'proba_totales', statement: "La formule des probabilités totales s'utilise souvent avec :", choices: ["une dérivée", "un arbre pondéré", "une droite", "une intégrale"], correct: 1, explanation: "L'arbre permet de visualiser les partitions de l'univers." },
  { id: 'Q29', chapterId: 'C32', skillType: 'automatisme', difficulty: 2, bacPriority: 5, skillTag: 'variance_binomiale', statement: "La variance d'une loi binomiale $B(n,p)$ est :", choices: ["$np$", "$np(1-p)$", "$n(1-p)$", "$p(1-p)$"], correct: 1, explanation: "Formule du cours pour la variance." },
  { id: 'Q30', chapterId: 'C35', skillType: 'raisonnement', difficulty: 3, bacPriority: 3, skillTag: 'bienayme_tchebychev', statement: "L'inégalité de Bienaymé-Tchebychev permet de :", choices: ["calculer une proba exacte", "majorer la proba d'un écart à l'espérance", "trouver l'espérance", "calculer la variance"], correct: 1, explanation: "Elle fournit une borne supérieure sans connaître la loi exacte." },
  { id: 'Q31', chapterId: 'C17', skillType: 'méthode', difficulty: 1, bacPriority: 5, skillTag: 'def_plan', statement: "Dans l'espace, un plan peut être défini par :", choices: ["1 point et 1 vecteur", "1 point et 2 vecteurs non colinéaires", "1 seul vecteur", "2 points"], correct: 1, explanation: "Il faut une origine et deux directions d'espace." },
  { id: 'Q32', chapterId: 'C19', skillType: 'automatisme', difficulty: 1, bacPriority: 5, skillTag: 'produit_scalaire_coord', statement: "Si $\\vec{u}(x,y,z)$ et $\\vec{v}(x',y',z')$ en repère orthonormé, $\\vec{u} \\cdot \\vec{v} =$ :", choices: ["$x+x'+y+y'+z+z'$", "$xx'+yy'+zz'$", "$xy+yz$", "$0$"], correct: 1, explanation: "Expression analytique du produit scalaire." },
  { id: 'Q33', chapterId: 'C20', skillType: 'méthode', difficulty: 1, bacPriority: 5, skillTag: 'vecteurs_orthogonaux', statement: "Deux vecteurs $\\vec{u}$ et $\\vec{v}$ sont orthogonaux si et seulement si :", choices: ["$\\vec{u} \\cdot \\vec{v} = 1$", "$\\vec{u} \\cdot \\vec{v} = 0$", "ils sont colinéaires", "leurs normes sont égales"], correct: 1, explanation: "Caractérisation fondamentale de l'orthogonalité." },
  { id: 'Q34', chapterId: 'C21', skillType: 'raisonnement', difficulty: 2, bacPriority: 5, skillTag: 'vecteur_normal', statement: "Un vecteur normal à un plan est :", choices: ["parallèle au plan", "orthogonal à tous les vecteurs du plan", "nul", "inclus dans le plan"], correct: 1, explanation: "Définition du vecteur normal." },
  { id: 'Q35', chapterId: 'C16', skillType: 'automatisme', difficulty: 1, bacPriority: 4, skillTag: 'coord_vecteur', statement: "Si $A(1,2,3)$ et $B(4,5,6)$, le vecteur $\\vec{AB}$ a pour coordonnées :", choices: ["$(3,3,3)$", "$(-3,-3,-3)$", "$(5,7,9)$", "$(4,10,18)$"], correct: 0, explanation: "Coordonnées de B moins coordonnées de A." },
  { id: 'Q36', chapterId: 'C16', skillType: 'raisonnement', difficulty: 2, bacPriority: 4, skillTag: 'vecteurs_coplanaires', statement: "Trois vecteurs sont coplanaires si :", choices: ["ils sont orthogonaux deux à deux", "l'un s'exprime comme combinaison linéaire des deux autres", "ils ont la même norme", "leur somme est nulle"], correct: 1, explanation: "Traduction de l'appartenance à un même plan vectoriel." },
  { id: 'Q37', chapterId: 'C23', skillType: 'méthode', difficulty: 2, bacPriority: 5, skillTag: 'equation_plan', statement: "Le plan d'équation $2x - y + 3z - 5 = 0$ a pour vecteur normal :", choices: ["$(2,-1,3)$", "$(-1,3,-5)$", "$(x,y,z)$", "$(2,1,-3)$"], correct: 0, explanation: "Les coefficients $a,b,c$ donnent le vecteur normal." },
  { id: 'Q38', chapterId: 'C22', skillType: 'méthode', difficulty: 2, bacPriority: 5, skillTag: 'droite_parametrique', statement: "Une représentation paramétrique de droite nécessite :", choices: ["2 vecteurs directeurs", "1 point et 1 vecteur directeur", "1 vecteur normal", "3 points"], correct: 1, explanation: "Une origine et une direction suffisent." },
  { id: 'Q39', chapterId: 'C22', skillType: 'méthode', difficulty: 3, bacPriority: 5, skillTag: 'appartenance_droite', statement: "Pour vérifier si un point appartient à une droite paramétrée, il faut :", choices: ["trouver un même paramètre $t$ pour les 3 coordonnées", "calculer la norme", "vérifier que $x+y+z=0$", "dériver l'équation"], correct: 0, explanation: "Il faut une cohérence du paramètre de temps $t$." },
  { id: 'Q40', chapterId: 'C24', skillType: 'raisonnement', difficulty: 2, bacPriority: 4, skillTag: 'projete_orthogonal', statement: "Le projeté orthogonal de $M$ sur un plan $P$ est :", choices: ["le point de $P$ le plus éloigné de $M$", "le point de $P$ le plus proche de $M$", "toujours l'origine", "le milieu de la droite"], correct: 1, explanation: "Il minimise la distance entre le point et le plan." },
  { id: 'Q41', chapterId: 'C26', skillType: 'raisonnement', difficulty: 3, bacPriority: 4, skillTag: 'positions_relatives', statement: "Deux droites de l'espace peuvent être :", choices: ["uniquement sécantes ou parallèles", "sécantes, parallèles ou non coplanaires", "toujours perpendiculaires", "toujours confondues"], correct: 1, explanation: "La particularité de la 3D est d'autoriser des droites ni sécantes ni parallèles." },
  { id: 'Q42', chapterId: 'C25', skillType: 'méthode', difficulty: 3, bacPriority: 3, skillTag: 'distance_point_plan', statement: "La distance d'un point à un plan se calcule via :", choices: ["le produit scalaire avec le vecteur normal", "l'aire du triangle", "le volume d'un cube", "une dérivée"], correct: 0, explanation: "Ou via la formule directe $\\frac{|ax+by+cz+d|}{\\sqrt{a^2+b^2+c^2}}$." },
  { id: 'Q43', chapterId: 'C38', skillType: 'méthode', difficulty: 2, bacPriority: 4, skillTag: 'boucle_while', statement: "Une boucle `while` est adaptée lorsqu'on :", choices: ["connaît le nombre d'itérations", "répète tant qu'une condition est vraie", "calcule une dérivée", "fait un produit scalaire"], correct: 1, explanation: "C'est une boucle conditionnelle, non bornée." },
  { id: 'Q44', chapterId: 'C41', skillType: 'méthode', difficulty: 3, bacPriority: 5, skillTag: 'algo_seuil', statement: "Un algorithme de seuil consiste à :", choices: ["chercher le premier rang vérifiant une condition", "calculer $u_0$", "résoudre une équation", "tracer un cercle"], correct: 0, explanation: "On utilise généralement un `while(u < seuil)`." },
  { id: 'Q45', chapterId: 'C49', skillType: 'raisonnement', difficulty: 2, bacPriority: 4, skillTag: 'contre_exemple', statement: "Pour montrer qu'une proposition universelle est fausse, on utilise :", choices: ["un exemple favorable", "un contre-exemple", "la récurrence", "le TVI"], correct: 1, explanation: "Un seul cas contraire suffit à infirmer le 'Pour tout'." },
  { id: 'Q46', chapterId: 'C46', skillType: 'raisonnement', difficulty: 3, bacPriority: 3, skillTag: 'contraposee', statement: "La contraposée de ($A \\implies B$) est :", choices: ["$B \\implies A$", "non $A \\implies$ non $B$", "non $B \\implies$ non $A$", "$A$ et non $B$"], correct: 2, explanation: "C'est l'équivalence logique fondamentale." },
  { id: 'Q47', chapterId: 'C48', skillType: 'raisonnement', difficulty: 3, bacPriority: 3, skillTag: 'negation_quantificateurs', statement: "La négation de 'Pour tout $x, f(x)>0$' est :", choices: ["Pour tout $x, f(x)\\le 0$", "Il existe $x$ tel que $f(x)\\le 0$", "Il existe $x$ tel que $f(x)<0$", "Aucun $x$ ne vérifie $f(x)>0$"], correct: 1, explanation: "Le 'Pour tout' devient 'Il existe' et l'inégalité s'inverse." },
  { id: 'Q48', chapterId: 'C42', skillType: 'méthode', difficulty: 4, bacPriority: 4, skillTag: 'dichotomie', statement: "La méthode de dichotomie utilise le fait que la fonction change de signe et est :", choices: ["dérivable", "constante", "continue", "périodique"], correct: 2, explanation: "Elle s'appuie sur le théorème des valeurs intermédiaires." },
];

export const QUESTIONS_OPEN: OpenQuestion[] = [
  { id: 'O1', chapterIds: ['C1','C2'], title: 'Ex. 1 - Suites & Récurrence', maxPoints: 7,
    statement: "Soit $u_0 = 1$ et $u_{n+1} = \\frac{1}{2} u_n + 3$. \n1. Calculer $u_1, u_2$. \n2. Montrer par récurrence que $u_n < 6$.\n3. Montrer que $(u_n)$ est croissante.\n4. En déduire sa limite.",
    rubrics: [ {label: "Calculs u1/u2", points: 1}, {label: "Init récurrence", points: 1}, {label: "Hérédité récurrence", points: 2}, {label: "Monotonie", points: 1.5}, {label: "Conclusion Limite", points: 1.5} ] },
  { id: 'O2', chapterIds: ['C4','C5'], title: 'Ex. 2 - Étude de fonction', maxPoints: 8,
    statement: "Soit $f(x) = x^2 e^{-x}$.\n1. Calculer $f'(x)$.\n2. Dresser le tableau de variations.\n3. Déterminer la limite en $+\\infty$.",
    rubrics: [ {label: "Formule (uv)'", points: 2}, {label: "Calcul f'(x)", points: 2}, {label: "Signe et Variations", points: 2}, {label: "Limite (croissances comp.)", points: 2} ] },
  { id: 'O3', chapterIds: ['C29','C32'], title: 'Ex. 3 - Loi binomiale', maxPoints: 6,
    statement: "On prélève 100 composants. Proba défectueux = 0.03. $X$ = nb défectueux.\n1. Justifier la loi binomiale.\n2. Calculer $P(X=0)$.\n3. Calculer espérance et variance.",
    rubrics: [ {label: "Justification (indép/succès)", points: 2}, {label: "Calcul P(X=0)", points: 2}, {label: "Espérance", points: 1}, {label: "Variance", points: 1} ] },
  { id: 'O4', chapterIds: ['C16','C23'], title: 'Ex. 4 - Géométrie Espace', maxPoints: 8,
    statement: "On donne $A(1,0,2)$, $B(3,1,4)$, $C(0,2,1)$.\n1. Coordonnées de $\\vec{AB}$ et $\\vec{AC}$.\n2. Calculer $\\vec{AB} \\cdot \\vec{AC}$.\n3. Équation du plan passant par $A$ de vecteur normal $\\vec{n}(1,-2,3)$.",
    rubrics: [ {label: "Coordonnées vecteurs", points: 2}, {label: "Produit scalaire", points: 2}, {label: "Structure équation plan", points: 2}, {label: "Résolution constante d", points: 2} ] },
  { id: 'O5', chapterIds: ['C8','C7'], title: 'Ex. 5 - Logarithme & TVI', maxPoints: 7,
    statement: "Soit $g(x) = \\ln(x) - \\frac{x}{2}$ sur $]0,+\\infty[$.\n1. Calculer $g'(x)$ et variations.\n2. Montrer que $g(x)=0$ a 2 solutions.\n3. Donner un encadrement.",
    rubrics: [ {label: "Calcul g'(x)", points: 1.5}, {label: "Variations", points: 1.5}, {label: "Conditions TVI", points: 2}, {label: "Application stricte TVI", points: 1}, {label: "Encadrement calculatrice", points: 1} ] },
  { id: 'O6', chapterIds: ['C6'], title: 'Ex. 6 - Convexité', maxPoints: 6,
    statement: "Soit $h(x) = x^3 - 3x^2 + 2$.\n1. Calculer $h''(x)$.\n2. Déterminer les intervalles de convexité.\n3. Préciser le(s) point(s) d'inflexion.",
    rubrics: [ {label: "Dérivée première", points: 1}, {label: "Dérivée seconde", points: 2}, {label: "Signe et convexité", points: 2}, {label: "Point d'inflexion", points: 1} ] },
  { id: 'O7', chapterIds: ['C10','C12'], title: 'Ex. 7 - Intégrales', maxPoints: 6,
    statement: "1. Calculer $\\int_0^1 (3x^2+2x+1) dx$.\n2. Primitive de $\\frac{\\ln(x)}{x}$ ?\n3. Calculer $\\int_1^e \\frac{\\ln(x)}{x} dx$.",
    rubrics: [ {label: "Primitive polynomiale", points: 1}, {label: "Calcul intégrale 1", points: 1}, {label: "Forme u'u", points: 2}, {label: "Calcul intégrale 2", points: 2} ] },
  { id: 'O8', chapterIds: ['C41'], title: 'Ex. 8 - Algorithmique (Seuil)', maxPoints: 4,
    statement: "Soit $u_0 = 2$ et $u_{n+1} = 1.2u_n + 5$.\nObjectif : premier $n$ tel que $u_n > 100$.\nÉcrire la boucle `while` en Python complétant :\n`u = 2`\n`n = 0`\n`while ... :`\n   `u = ...`\n   `n = ...`",
    rubrics: [ {label: "Condition while", points: 1.5}, {label: "Affectation u", points: 1.5}, {label: "Incrémentation n", points: 1} ] },
];

export const ERROR_TYPES: string[] = [
  "Erreur de calcul", "Erreur de méthode", "Erreur de rédaction",
  "Absence de justification", "Confusion de notion", "Blocage au démarrage",
  "Théorème mal utilisé", "Interprétation graphique", "Mauvaise utilisation calculatrice", "Raisonnement incomplet"
];

export const DISCOVERY_CLUSTERS: DiscoveryCluster[] = [
  { id: 'suites', title: 'Suites & Récurrence', ids: ['C1','C2'] },
  { id: 'ln_tvi', title: 'Logarithme & TVI', ids: ['C8','C7'] },
  { id: 'prim_int', title: 'Primitives & Intégrales', ids: ['C10','C12','C13','C14'] },
  { id: 'geo', title: "Géométrie dans l'Espace", ids: ['C16','C17','C19','C20','C21','C22','C23','C24'] },
  { id: 'proba', title: 'Probabilités', ids: ['C28','C29','C30','C31','C32'] },
  { id: 'algo', title: 'Algorithmique', ids: ['C38','C41','C42'] },
];
