import { randomUUID } from 'node:crypto';
const testPassword = ['Synthetic', randomUUID()].join('-');
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { SignInForm } from '@/app/auth/signin/SignInForm';
import { signIn, getSession } from 'next-auth/react';
const push=jest.fn();
jest.mock('next/navigation',()=>({useRouter:()=>({push}),useSearchParams:()=>new URLSearchParams('callbackUrl=%2Fdashboard%2Fparent%2Finscription')}));
jest.mock('next-auth/react',()=>({signIn:jest.fn(),getSession:jest.fn()}));
jest.mock('@/lib/analytics',()=>({track:{signinAttempt:jest.fn(),signinError:jest.fn(),signinSuccess:jest.fn()}}));
it('uses neutral activation request copy before the delivery channel is known', async () => {
 (signIn as jest.Mock).mockResolvedValue({ error: 'CredentialsSignin' });
 render(<SignInForm />);
 const input = screen.getByLabelText('Téléphone WhatsApp ou email');
 fireEvent.change(input, { target: { value: '+21699192829' } });
 fireEvent.change(screen.getByLabelText('Mot de Passe'), { target: { value: testPassword } });
 fireEvent.submit(input.closest('form')!);
 fireEvent.click(await screen.findByRole('button', { name: "Demander l'activation de mon accès" }));
 expect(screen.getByLabelText("Demande d'activation")).toBeVisible();
 fireEvent.change(screen.getByLabelText("Demande d'activation"), { target: { value: '' } });
 fireEvent.change(screen.getByLabelText('Téléphone WhatsApp ou email'), { target: { value: '' } });
 fireEvent.click(screen.getByRole('button', { name: "Demander l'activation" }));
 expect(await screen.findByText("Saisissez votre téléphone ou email pour demander l'activation de votre accès.")).toBeVisible();
 expect(screen.queryByText(/renvoyer (un|le) lien/i)).not.toBeInTheDocument();
});
it('submits a phone identifier and retains the parent completion callback',async()=>{
 (signIn as jest.Mock).mockResolvedValue({ok:true});(getSession as jest.Mock).mockResolvedValue({user:{role:'PARENT'}});
 render(<SignInForm/>);
 const identifier=screen.getByLabelText('Téléphone WhatsApp ou email');
 expect(identifier).toHaveAttribute('type','text');
 fireEvent.change(identifier,{target:{value:'+21699192829'}});
 fireEvent.change(screen.getByLabelText('Mot de Passe'),{target:{value:testPassword}});
 fireEvent.submit(identifier.closest('form')!);
 await waitFor(()=>expect(signIn).toHaveBeenCalledWith('credentials',expect.objectContaining({identifier:'+21699192829',password:testPassword})));
 expect(push).toHaveBeenCalledWith('/dashboard/parent/inscription');
});
it('offers manual assistance from sign-in activation renewal', async () => {
 (signIn as jest.Mock).mockResolvedValue({ error: 'CredentialsSignin' });
 const fetchMock = jest.spyOn(global, 'fetch').mockResolvedValue({ ok: true, json: async () => ({ success: true, deliveryMode: 'MANUAL' }) } as Response);
 render(<SignInForm />);
 const input = screen.getByLabelText('Téléphone WhatsApp ou email');
 fireEvent.change(input, { target: { value: '+21699192829' } });
 fireEvent.change(screen.getByLabelText('Mot de Passe'), { target: { value: testPassword } });
 fireEvent.submit(input.closest('form')!);
 fireEvent.click(await screen.findByRole('button', { name: "Demander l'activation de mon accès" }));
 fireEvent.click(screen.getByRole('button', { name: "Demander l'activation" }));
 expect(await screen.findByRole('link', { name: 'Contacter l’assistante sur WhatsApp' })).toBeVisible();
 expect(screen.queryByText(/un nouveau lien a été envoyé/)).not.toBeInTheDocument();
 fetchMock.mockRestore();
});
