import type { PlanningDay } from "./types";

// SOURCE: Planning_v2, parcours STMG.
export const BASE_PLANNING: PlanningDay[] = [
  {
    id: "j0",
    label: "J0",
    date: "sam. 30/05",
    objective: "Diagnostic + profilage → profil, parcours et livret.",
    domainIds: [],
    automatismes: "30 items sans calculatrice, correction immédiate.",
    exercises: "4 exercices courts auto-évalués avec barème guidé.",
    homework: "Lecture de la fiche du domaine prioritaire #1.",
  },
  {
    id: "j1",
    label: "J1",
    date: "lun. 01/06",
    objective: "Domaine prioritaire #1 : cours ciblé, automatismes, exercice type EAM.",
    domainIds: ["fonctions"],
    automatismes: "Série chrono 12 items du domaine prioritaire.",
    exercises: "1 exercice Partie 2 contextualisé STMG.",
    homework: "15–20 min automatismes + 1 exercice court.",
  },
  {
    id: "j2",
    label: "J2",
    date: "mar. 02/06",
    objective: "Domaine prioritaire #2 avec reprise des erreurs J1.",
    domainIds: ["suites"],
    automatismes: "Série chrono mixte domaine #2 + erreurs J1.",
    exercises: "1 exercice Partie 2 et correction détaillée.",
    homework: "15–20 min automatismes + reprise des erreurs.",
  },
  {
    id: "j3",
    label: "J3",
    date: "mer. 03/06",
    objective: "Domaine #3 + bloc automatismes intensif Partie 1.",
    domainIds: ["statistiques"],
    automatismes: "Deux séries courtes, objectif régularité.",
    exercises: "1 exercice données ou probabilités selon diagnostic.",
    homework: "15–20 min automatismes + 1 exercice.",
  },
  {
    id: "j4",
    label: "J4",
    date: "jeu. 04/06",
    objective: "Domaines #4/#5 + 1 sujet zéro complet en conditions.",
    domainIds: ["probabilites", "algorithmique-information"],
    automatismes: "Échauffement 10 items sans calculatrice.",
    exercises: "Sujet zéro complet 2 h, sans calculatrice.",
    homework: "Correction + reprise des erreurs.",
  },
  {
    id: "j5",
    label: "J5",
    date: "ven. 05/06",
    objective: "Reprise ciblée + 2e sujet en conditions + stratégie jour J.",
    domainIds: [],
    automatismes: "Série mixte sur les erreurs résiduelles.",
    exercises: "Sujet en conditions puis correction priorisée.",
    homework: "Livret week-end : révision active légère.",
  },
  {
    id: "we",
    label: "WE",
    date: "06–07/06",
    objective: "Révision active légère : automatismes, 1 sujet, fiches stratégie, sommeil.",
    domainIds: [],
    automatismes: "Deux blocs de 15 minutes, sans pression.",
    exercises: "Un sujet ou demi-sujet selon fatigue.",
    homework: "Aucune charge nouvelle ; consolider et dormir.",
  },
  {
    id: "jour-j",
    label: "Jour J",
    date: "lun. 08/06",
    objective: "Épreuve Anticipée de Mathématiques.",
    domainIds: [],
    automatismes: "Partie 1 en premier, lecture attentive.",
    exercises: "Partie 2 : commencer par les questions directes.",
    homework: "Aucun.",
  },
];
